### ISSUE TITLE
MQTT subscriber 3.9.0 windows does not show any topics at all.

### ISSUE THREAD

**Issue by matthijsfh** [facontidavide/PlotJuggler#1006]
# Problem description

Running Windows 10.

Just upgraded from 3.6.0 to 3.9.0

But now MQTT dialog does not list any of the (persistent) topics. Closed, run 3.6, showing all topics. (needed 3.9 to be able to select more than 1 topic from the list).

So back to 3.6.0 for now.

**Comment by Valle125** [comment]
I can confirm the problem. I have the same issues on Win 11.

It seems that there are related issues on Linux. I can not connect to a local broker on Ubuntu 22. See screenshot below. It works flawlessly with MQTT Explorer. I'll try to debug the problem further and eventually submit a patch.

![Screenshot from 2024-09-17 18-36-38](https://github.com/user-attachments/assets/0ab379b3-ca49-4261-8459-59cea9978206)

**Comment by Valle125** [comment]
I've been debugging a bit today on my Linux  machine (Plotjuggler 3.9.1). When I open the MQTT plugin window and hit the connect/disconnect button repeatedly, Plotjuggler becomes stuck. The program flow seems to remain within mosquitto_connect_bind_v5() inside mqtt_client.cpp. I've tried to fix this by starting with a fresh mosquitto instance at each connection attempt, which seems to work. The program flow no longer locks up and I'm able to display data.

I'll test on windows in the next few days and submit a pull request when I'm confident with the patch.

**Comment by briha** [comment]
My colleagues and I were having the same issue. I had solved it by just using the paho mqtt library instead, but #1009 seems like a more robust solution!

**Comment by matthijsfh** [comment]
Tested on windows 10 and it does seem to work. Thanks!
