### ISSUE TITLE
Grey Plots, sometimes

### ISSUE THREAD

**Issue by twostripe** [facontidavide/PlotJuggler#102]
version: **1.7.1**
os: **ubuntu 16.04**

It's unclear why sometimes plots turn grey. Sometimes there are curves in them sometimes not. Seems to be associated with lack of use? When I put another curve in them they seem to turn white again.

![grey plots](https://user-images.githubusercontent.com/14950045/43975539-e323425c-9c92-11e8-994e-fc949b7c5f4e.png)

**Comment by facontidavide** [comment]
I need to find a way to reproduce this... any suggestion?

Can you record the steps you take using screen capture?

**Comment by facontidavide** [comment]
Fixed
