### ISSUE TITLE
No way to "clear buffer" while streaming

### ISSUE THREAD

**Issue by twostripe** [facontidavide/PlotJuggler#104]
version: **1.7.1**
os: **ubuntu 16.04**

There is currently no way to clear the buffer while streaming. The ideal case would be to have streaming data, then click a button to entirely clear the buffer, new data would continue to stream and all timeseries would start at 0.

This presents two issues, depending on whether you're playing back data from a bag or streaming data live.

**Streaming data live**
Issue: to clear the buffer, one must:

1. Streaming > Stop streaming
2. Streaming > Clear buffer
3. Streaming > Start: ROS_Topic_Streamer
4. [OK]

Seems fine but is annoying to have to do every time.

**Playing back from a bag**
If the buffer isn't cleared between bag playbacks, then

- any time series isn't offset anymore, making the data less useful
- any x/y plots (ie: non time-series plots) have a line drawn from the end of the first bag to the beginning of the second bag

We might assume that most people won't stream while replaying a bag, but this does often happen (if i'm wanting to visualize thing in RViz at the same time, for example). Though this case is a much lower priority, I'm leaving it on here so that it's on your radar.

**Comment by facontidavide** [comment]
About the two use cases.

__Streaming__: it makes lot of sense, I guess it can be implemented quite easily.

__Playing back from a bag__: I honestly don't see an easy solution that makes everyone happy.
It is the reason why I usually ask the user to delete the previous buffer. But I will think about it.

**Comment by facontidavide** [comment]
Hi,

since the __Playing back from a bag__ is a wontfix for the time being, I will close this issue.
If in the future you have a more concrete suggestion about that use case shall be addressed, let me know.

Cheers

**Comment by twostripe** [comment]
Makes sense, I figured that would be your choice.
