### ISSUE TITLE
Improvement: Font size adjustment

### ISSUE THREAD

**Issue by michael1874888** [facontidavide/PlotJuggler#106]
Hi @facontidavide ,
I think it would be great to be able to change the font size of the legend. In some cases (e.g. without any subplot),  the font size of the legend looks small. And it would also be convinient if we can change the position of the legend.

**Comment by facontidavide** [comment]
Sure, I will add this feature in the future, but probably not in PlotJuggler 1.X

Thanks for the suggestion

**Comment by facontidavide** [comment]
You can now resize the legend using **CTRL + Mouse Wheel.**

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/2822888/51692288-e2467a00-1ffc-11e9-86ae-e2eb7542f194.gif)

**Comment by michael1874888** [comment]
It looks great!

**Comment by idref** [comment]
Hi @facontidavide,
first of all, thx for this great tool !

I think it would be nice to be able to change the font size of the annotation of the axes and maybe the thickness of the lines as well. With many subplots the fonts are very small.

Is there a current way to do this?
Thank you !
