### ISSUE TITLE
Log scale plotting?

### ISSUE THREAD

**Issue by ahundt** [facontidavide/PlotJuggler#112]
Is it possible to plot data on a logarithmic scale? I've got a time series that decays exponentially, so the Y values go down from 1 to 10^-3 to 10^-6 as time proceeds linearly. Non-log plots just look like the value drops to zero and stays there. :-)

**Comment by ahundt** [comment]
ok cool thanks, enjoy your holiday!

**Comment by facontidavide** [comment]
I think this will serve only a tiny fraction of my users and I will probably not implement it. I am temporarily closing this issue.

**Comment by gitterspec** [comment]
Also very interested in this feature. Wondering if it might end up back on the roadmap?

**Comment by amilcarlucas** [comment]
same here

**Comment by edward9503** [comment]
Hi @facontidavide ,

I think there is a growing tendency for using the logarithm scale in streaming. It would be great if this feature can be added. Many thanks.

**Comment by sjs329** [comment]
+1 for log scale plotting!

**Comment by sneuro** [comment]
+1
Required function!

**Comment by naokiuchida** [comment]
+1 necessary feature!

**Comment by andrei-markov-emlid** [comment]
+1 Very useful feature

**Comment by facontidavide** [comment]
PR welcome

**Comment by Basilisvirus** [comment]
+1 Very useful feature
Would be happy to see logarithmic possibility in both X and Y axis.
