### ISSUE TITLE
Feature request: Multiply/Offset axis ticks

### ISSUE THREAD

**Issue by llvs** [facontidavide/PlotJuggler#116]
Dear Davide,
I have again a feature request: It would be very handy to be able to apply some kind of multiplication / offset removal to the values displayed on a per-plot basis.

Example 1: An angle value is given in radians and I want to have it displayed in degrees, i.e. I want to apply the transform "*180.0/pi" to the values.

Example 2: A value starts at large values and changes not so much from then on and I am only interested in the relative changes, not so much in the absolute value. Therefore, I would like to be able to remove the offset from the first value of the plot so that the plots start at zero.

Best regards

**Comment by facontidavide** [comment]
So you mean a offset in the Y axis (value) not the X Axis (time).

That will be possible once I merge the new branch https://github.com/facontidavide/PlotJuggler/tree/custom_math

You will be able to apply simple formulas that modify the value, being an offset the simplest one. Let me show you.

![selection_160](https://user-images.githubusercontent.com/2822888/47489576-3b104600-d847-11e8-8f21-ee861e18dfb4.png)
![selection_159](https://user-images.githubusercontent.com/2822888/47489577-3b104600-d847-11e8-909e-992a52e773bf.png)

**Comment by llvs** [comment]
Thank you! I will try that code branch.

**Comment by facontidavide** [comment]
Hi,

with the nex "custom plot" functionality, it is now possible to do what you mentioned.

Cheers

**Comment by llvs** [comment]
Thanks a lot!
