### ISSUE TITLE
Bug: Saved layout misses custom x-axis

### ISSUE THREAD

**Issue by llvs** [facontidavide/PlotJuggler#117]
Dear Davide,

sorry for being such a nuisance, but using PlotJuggler a lot recently shows a few quirks which I will report here.

The saved plot layouts seem to not include the information that a plot was using a custom x-axis that I dragged with the right mouse button onto another plot. After reloading the layout I have to re-apply that custom x-axis.

Best regards

**Comment by facontidavide** [comment]
I will check it out and see if I can reproduce it. Thanks for reporting

**Comment by facontidavide** [comment]
Fixed :)
