### ISSUE TITLE
Remove selected curves removes only clicked items

### ISSUE THREAD

**Issue by jaredkhan** [facontidavide/PlotJuggler#122]
Environment: Ubuntu 16.04
To reproduce:
- open plotjuggler with the dummy data
- drag many series onto the plot
- right click on the legend
- click 'remove curves'
- click and drag over the list of items to select them all
- click 'remove selected'
Expected:
- All highlighted rows will be removed
Actual:
- Only rows that have been clicked, resulting in the name being struck through, will be removed

I really like the click and drag selection, and we get this for free from qt.

I propose we forgo the strike through and just when 'remove selected' is clicked, find the items that are selected and remove them (rather than finding the ones that have strikethrough font).

I propose marking as 'help wanted' since it would be a good starter bug

**Comment by facontidavide** [comment]
Thank you very much for reporting. I will look into it

**Comment by facontidavide** [comment]
Fixed. Thank you for reporting, it was really ugly
