### ISSUE TITLE
Installation under ROS

### ISSUE THREAD

**Issue by galou** [facontidavide/PlotJuggler#13]
I have a doubt about the installation under ROS.

I clone the repository under `catkin_ws/src` and ran `catkin build` from catkin-tools. I guess this is correct as I can run `rosrun plotjuggler PlotJuggler`. Are these the only steps?

If I want to use PlotJuggler both with and without ROS, I guess I have to also make the classical installation. Am I right?

**Comment by facontidavide** [comment]
it should work now.

To compile WITHOUT ROS support when ROS is installed on your PC, you should comment this line in the CMakeLists.txt file

https://github.com/facontidavide/PlotJuggler/blob/master/CMakeLists.txt#L7
