### ISSUE TITLE
Autostart publishers from Layout file

### ISSUE THREAD

**Issue by bysteven** [facontidavide/PlotJuggler#130]
I am setting up an automated system for rosbag analysis. I am launching plotjuggler with -l and -d, afterwards go to the menu to start the publishers. It would be really awesome if there was an option to autostart the publishers (all topics, or with a python statement like for rosbag filter).

For example:
rosrun plotjuggler PlotJuggler -l some_config -d some_file -p all

**Comment by bysteven** [comment]
That would be evenly awesome.

**Comment by facontidavide** [comment]
ok, I will add it to my TODo list

**Comment by bysteven** [comment]
Great, thank you!

**Comment by bysteven** [comment]
How can I tip you with a beer? Do you have a XRP tipbot address or similar?

**Comment by facontidavide** [comment]
My PayPal account can be found in the Readme file. Cheers!

**Comment by facontidavide** [comment]
feature has been implemented in branch "parsers" that will be merged soon
