### ISSUE TITLE
[TODO]: Tree view (issue #134 and #74)

### ISSUE THREAD

**Issue by facontidavide** [facontidavide/PlotJuggler#140]
Add a way to group timeseries into groups and show them in a tree view with a single depth level.

for instance, give the topic __/turtle1/pose__

istead of :

>       /turtle1/pose/linear_velocity
>       /turtle1/pose/theta
>       /turtle1/pose/ x
>       /turtle1/pose/y

Weshould see a tree with this structure

>     /turtle1/pose
>     -- linear_velocity
>     -- theta
>     -- x
>     -- y

**Comment by bresch** [comment]
Related to that issue, in `.ulg` files, the signals that have more than a single depth level are not shown properly:

Currently in PlotJuggler:
![position_setpoint_triplet_juggler](https://user-images.githubusercontent.com/14822839/53580598-46b8a400-3b7c-11e9-90cf-7a42ac4e9b49.png)

and those triplets should contain:
![position_setpoint_triplet](https://user-images.githubusercontent.com/14822839/53580608-4fa97580-3b7c-11e9-9654-4a0c74c05cfa.png)

**Comment by facontidavide** [comment]
@bres The error is not related to this issue. I will try to to fix it though

**Comment by facontidavide** [comment]
I am extremely excited to close this issue
