### ISSUE TITLE
[Feature request] Support multiple instances of the same message

### ISSUE THREAD

**Issue by bresch** [facontidavide/PlotJuggler#146]
Hi, I'm trying to move from FlightPlot to PlotJuggler to read `.ulg` files as I see a huge potential in that project.

The issue is the following:
Some messages have multiple instances and they are plotted as a single signal:
![multiple_gps](https://user-images.githubusercontent.com/14822839/53172930-d2fc2180-35e6-11e9-8047-17d1a179ac4b.png)

The following result is expected:
![multiple_gps_flightplot](https://user-images.githubusercontent.com/14822839/53172948-e3140100-35e6-11e9-8da1-086da41f4f9d.png)

For completeness, this is the log file:
https://logs.px4.io/plot_app?log=412f7d6b-3d3f-42e9-b04f-c9a55e16bf9d

Many thanks!

**Comment by facontidavide** [comment]
No problem, I can fix this. Can you please send me the file to be able to reproduce this?

**Comment by facontidavide** [comment]
No problem, I should be able to fix this easily. Thanks for reporting

**Comment by facontidavide** [comment]
Fixed it:

![image](https://user-images.githubusercontent.com/2822888/53181557-10b57600-35f8-11e9-87f2-14987f4b8310.png)

Can you please check out the last commit and test it?

**Comment by facontidavide** [comment]
I am closing it. Let me know if you have any additional issue.

i will soon release 2.1.4 with this improvement

**Comment by bresch** [comment]
@facontidavide Awesome! That was quick!
