### ISSUE TITLE
Error parsing position_setpoint_triplet

### ISSUE THREAD

**Issue by facontidavide** [facontidavide/PlotJuggler#151]
@bresch

![ulog setposition](https://user-images.githubusercontent.com/14822839/53580608-4fa97580-3b7c-11e9-9654-4a0c74c05cfa.png)

**Comment by facontidavide** [comment]
that was though....

**Comment by bresch** [comment]
@facontidavide Works perfectly, thanks!

**Comment by facontidavide** [comment]
You are welcome. I must confess I skimmed through the documentation of the Ulog format and I did not realized that a Format can contain other Format in a nested way.

Solved it with classical recursion ;)

**Comment by junwoo091400** [comment]
> You are welcome. I must confess I skimmed through the documentation of the Ulog format and I did not realized that a Format can contain other Format in a nested way.

FYI the ULog Format doc got a recent upgrade, in case you are interested 😉 @facontidavide 
https://docs.px4.io/main/en/dev_log/ulog_file_format.html
