### ISSUE TITLE
Save plots does not increment name

### ISSUE THREAD

**Issue by bresch** [facontidavide/PlotJuggler#155]
Hello, I find something not really convenient while saving plots as images.

Description:
The `Save all plot tabs as images` function always tries to save the first plot as `01_plot.png`. If that file already exists, it asks to overwrite it.

Possible solutions:
1. Ask the user to enter a filename, if it exists, ask to overwrite it
2. Increment the number is the file already exists

Many thanks!

**Comment by facontidavide** [comment]
Hi, 

the best solution in my opinion is to add a prefix with the date in **YYYY_MM_DD_hh_mm** format.

If anyone wants to send a PR... be my guest ;)

**Comment by bresch** [comment]
That's a good idea, I'll do that
