### ISSUE TITLE
Topic with a float32 NaN leads to crash 

### ISSUE THREAD

**Issue by FabianUhl** [facontidavide/PlotJuggler#156]
Hi, 
I m currently working at project with a sensor Battery state msg.  If I  preload a float32 with a NaN and try to plot this msg with plotjuggler, it will run into an issue. This Issue can be reproduced with

 `rostopic pub -r 1 /test std_msgs/Float32 '.NAN'` 

Error Report:
> Failed to launch the streamer ....
terminate called after throwing an instance of 'RosIntrospection::RangeException'
what():  Floating point truncated

It is exclusively an issue with float32. The same with float64 works fine.

Best regards

**Comment by facontidavide** [comment]
I will have a look at this today. Thanks for reporting

**Comment by facontidavide** [comment]
Fixed. NAN and INF should be ignored now
