### ISSUE TITLE
Comparing data in stacked plots can be difficult due to misalignment

### ISSUE THREAD

**Issue by skohlbr** [facontidavide/PlotJuggler#160]
When plotting data with different magnitudes on their y  scales into two plots in separate rows stacked above each other, the fact that the y axis legend is wider for one of them means that the grid on the plots is slightly offset between them, which makes comparing values a lot more difficult than it could be.

In principle, the vertical time tracker could be used, but with very long bag files it cannot be controlled accurately enough with the slider at the bottom to be useful. So either aligning plots, or being able to move the vertical tracker using the mouse would make this comparison use case easier.

See plot below (and the hand-drawn red marking on the left middle showing the offset)
![plot_offset](https://user-images.githubusercontent.com/205963/54741753-acb6ab00-4bbf-11e9-91be-d3baed813a8e.png)

This is using PlotJuggler from source/master.

**Comment by facontidavide** [comment]
Good point. I should take care of this at some point

**Comment by aeudes** [comment]
for completeness, please also note that the tracker could already be move with shift+click

**Comment by skohlbr** [comment]
> for completeness, please also note that the tracker could already be move with shift+click

Oh, I missed that, excellent :)

**Comment by facontidavide** [comment]
@aeudes thanks for pointing that out. As documented in the Cheatsheet, the most convenient way to move the tracker is Shift + Left Mouse

**Comment by facontidavide** [comment]
I will not work on this issue, probably. Closing it for the time being
