### ISSUE TITLE
AppImage fails to load ROS related plugins and/or ROS bags

### ISSUE THREAD

**Issue by ndepal** [facontidavide/PlotJuggler#166]
I just started using PlotJuggler to analyze PX4 .ulg files.

I now wanted to open a ROS bag. In the `File > Load Data` dialog, I can only select "Files of type" `*.csv, *.ulg` and therefore can't load a ROS bag file.

I'm sure I'm missing something obvious. What do I need to do?
Thanks!

This is with versions 2.1.5 and 2.1.8.

**Comment by facontidavide** [comment]
Are you compiling it or using the AppImages?

**Comment by ndepal** [comment]
AppImages

**Comment by facontidavide** [comment]
take a look at the console message, this is the "correct one":

> "libDataLoadCSV.so" : is a DataLoader plugin
> "libDataLoadROS.so" : is a DataLoader plugin
> "libDataLoadULog.so" : is a DataLoader plugin
> "libDataStreamROS.so" : is a DataStreamer plugin
> "libDataStreamSample.so" : is a DataStreamer plugin
> "libDataStreamSample.so" ...but will be ignored unless the argument -t is used.
> "libRosoutPublisher.so" : is a StatePublisher plugin
> "libRosTopicPublisher.so" : is a StatePublisher plugin

**Comment by ndepal** [comment]
```"libDataLoadCSV.so" : is a DataLoader plugin
"libDataLoadROS.so" :  "Cannot load library /tmp/.mount_PlotJuRqpCar/libDataLoadROS.so: (libros_type_introspection.so: cannot open shared object file: No such file or directory)"
"libDataLoadULog.so" : is a DataLoader plugin
"libDataStreamROS.so" :  "Cannot load library /tmp/.mount_PlotJuRqpCar/libDataStreamROS.so: (libros_type_introspection.so: cannot open shared object file: No such file or directory)"
"libDataStreamSample.so" : is a DataStreamer plugin
"libDataStreamSample.so" ...but will be ignored unless the argument -t is used.
"libRosoutPublisher.so" : is a StatePublisher plugin
"libRosTopicPublisher.so" :  "Cannot load library /tmp/.mount_PlotJuRqpCar/libRosTopicPublisher.so: (libros_type_introspection.so: cannot open shared object file: No such file or directory)"
```

**Comment by facontidavide** [comment]
it is what I expected :(

Do:
      sudo apt install ros-kinetic-ros-type-introspection 

Changing __kinetic__ with your ROS distro if necessary. I haven't been able to fix this in the AppImage yet.

**Comment by ndepal** [comment]
That fixed it. Thanks for the fast reponse!

**Comment by ndepal** [comment]
Well actually, it works if I run PlotJuggler form a terminal. If I use a `.desktop` file to run it, it does not work...

**Comment by facontidavide** [comment]
The right solution would be to embed the ros_type_introspection library into the AppImage, but I haven't managed to do it for some reason.... any help is welcomed.

These are the steps I follow to create the AppImage: https://github.com/facontidavide/PlotJuggler/blob/master/appimage_howto.md

**Comment by facontidavide** [comment]
Fixed!!!!!!!!!!!

**Comment by facontidavide** [comment]
I completely lied to you. App Image 2.3.6 is the first one that really fix this issue
