### ISSUE TITLE
Feature request: Message filter fuzzy matching

### ISSUE THREAD

**Issue by ndepal** [facontidavide/PlotJuggler#167]
Being able to filter messages contained in a log is a great feature.
PJ already has several options for how to filter the list.

I'd love to see the option for fuzzy matching.
I.e. `loposz` would show the message `local_position/z`

**Comment by ndepal** [comment]
Looking at the source I realized that this pretty much exists when using the `contains` setting and using spaces in the search term.
I.e. `lo pos z` matches `local_position/z`.

**Comment by facontidavide** [comment]
The "contains" filter is the one I use 99% of the time myself ;)
