### ISSUE TITLE
Ros topic selection window is not sorted

### ISSUE THREAD

**Issue by uliklank** [facontidavide/PlotJuggler#17]
A sorting would help for a large number of topics.
A selection of multiple topics would be helpful, too.

**Comment by facontidavide** [comment]
Thanks for the suggestion, I will take a look at it.
I guess you refer to the streaming window, not the rosbag loading

**Comment by facontidavide** [comment]
Done!

By the way, to select multiple topics, just keep CTRL-L pressed.
