### ISSUE TITLE
ULog: Error loading definitions

### ISSUE THREAD

**Issue by yutaoliu** [facontidavide/PlotJuggler#170]
The plugin [DataLoad ULog] throw the exception.
Running the binary from windows 10 installation.

**Comment by facontidavide** [comment]
I should update the windows binary to the latest version.

Can you please share a ULOG file that I can use to reproduce the issue?

**Comment by facontidavide** [comment]
Since you haven't answered, I am closing this issue.

**Comment by CornerOfSkyline** [comment]
[demo.zip](https://github.com/facontidavide/PlotJuggler/files/3514349/demo.zip)
@facontidavide this is a ulog file. The problem is still on windows 10.

**Comment by copterspace** [comment]
Same problem on Windows 10 x64, just tried, here's log file.
![изображение](https://user-images.githubusercontent.com/38784273/73527317-4d0a6c80-442c-11ea-8219-ec01e7e02593.png)

[log_76_2019-11-14-12-11-44.zip](https://github.com/facontidavide/PlotJuggler/files/4138470/log_76_2019-11-14-12-11-44.zip)

**Comment by facontidavide** [comment]
even if I am not so much into ULog file support, I will try to have a look at this... one of these days ;)

**Comment by ayberkozgur** [comment]
Same problem persisting on 2.8.2.

**Comment by facontidavide** [comment]
I am currently focused on plotjuggler 3.0

If people want / need to prioritize this feature or others, consider becoming a sponsor ☺️

**Comment by facontidavide** [comment]
I am glad to say that the problem has been fixed

**Comment by vserluco** [comment]
I am having this same issue today. Not sure if something broke
