### ISSUE TITLE
Plot Axis Don't Render on OSX

### ISSUE THREAD

**Issue by keenanjohnson** [facontidavide/PlotJuggler#171]
![image](https://user-images.githubusercontent.com/2559382/57736834-549ba280-765e-11e9-884d-103cd03410aa.png)

**Comment by keenanjohnson** [comment]
I built Plot Juggler for OSX and I'm using it to render ulog files. However, it doesn't seem to render the plot axis haha. See my picture above.

Perhaps this is a font issue or something? Any ideas?

**Comment by keenanjohnson** [comment]
Here's my std out:

Keenans-MacBook-Pro-2:~ keenanjohnson$ /Users/keenanjohnson/Desktop/PlotJuggler-master/bin/PlotJuggler ; exit;
"libDataLoadCSV.dylib" : is a DataLoader plugin
"libDataLoadULog.dylib" : is a DataLoader plugin
"libDataStreamSample.dylib" : is a DataStreamer plugin
"libDataStreamSample.dylib" ...but will be ignored unless the argument -t is used.
"libDataStreamWebSocket.dylib" : is a DataStreamer plugin
objc[49271]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff988d53c8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x1139b0f50). One of the two will be used. Which one is undefined.

**Comment by facontidavide** [comment]
Sorry, I am afraid that I have no clue and I can hardly debug it, since I don't have OSX....

If anyone has any clue, please contribute.

**Comment by keenanjohnson** [comment]
Any tips on how to debug it? I’m happy to help, just need a few pointers

**Comment by facontidavide** [comment]
I honestly have no clue. I am using QWT https://qwt.sourceforge.io/

You might want to download it and check if the examples work correctly or not.

**Comment by keenanjohnson** [comment]
Ok thanks very much! I'm going to poke around and see if i can discover the issue.

**Comment by facontidavide** [comment]
I will never support OSX, so I am temporarily closing this issue.
If anyone can submit a fix, he/she is welcome.
