### ISSUE TITLE
Repeated start and stop of streaming does sometimes freeze the output.

### ISSUE THREAD

**Issue by uliklank** [facontidavide/PlotJuggler#18]
When plotting multiple ros topics, and starting and stopping the streaming, the program seems to fall into a mode, streaming can not activated successfully.

No obvious reset returns to a valid state.

**Comment by facontidavide** [comment]
Is there any way I can recreate this problem locally on my machine?
Any suggestion?

Would you be able to take a screencast of the behavior using something like this ?

http://www.omgubuntu.co.uk/2013/12/simple-screen-recorder-linux

**Comment by facontidavide** [comment]
I made few changes to the way that streaming coordinates with the main thread.

Can you pull the changes from master and tell me if you still experience the problem?

**Comment by facontidavide** [comment]
Since I made several changes in the last weeks, I don't know if you still has the same problem or not...
I will temporarily close this issue. Don't hesitate to reopen it if the problem persists.
