### ISSUE TITLE
Feature Request: Export Data

### ISSUE THREAD

**Issue by atyshka** [facontidavide/PlotJuggler#182]
Thanks for the great work on this tool, I've found it invaluable in visualizing autonomous vehicle data. With the introduction of custom timeseries, is there a way to export the data? Since we can now do some really cool math inside Plotjuggler it would be great to be able to export our custom data to something like a CSV file.

**Comment by facontidavide** [comment]
Sorry for the late reply.

This can be a valuable addition, but it will take me a while before I implement it, since i have other changes in the pipeline that come first.

**Comment by facontidavide** [comment]
Done
