### ISSUE TITLE
Server Down?

### ISSUE THREAD

**Issue by prasgane** [facontidavide/PlotJuggler#186]
Hi 
I am trying to install PlotJuggler using the 
`sudo apt-get install ros-kinetic-plotjuggler`

and it keeps returning:

> Err:1 http://packages.ros.org/ros/ubuntu xenial/main amd64 ros-kinetic-plotjuggler amd64 2.1.10-0xenial-20190417-120349-0800
  404  Not Found [IP: 64.50.236.52 80]
This error shows up when you try to install ros-type-introspection too.

**Comment by 1r0b1n0** [comment]
Your apt database is pointing to an old version, executing "sudo apt update" should fix this.
If apt is complaining the the key of the ROS repository is unknown you'll have to update it ( https://discourse.ros.org/t/new-gpg-keys-deployed-for-packages-ros-org/9454 )
