### ISSUE TITLE
Unable to find Add Prefix

### ISSUE THREAD

**Issue by senoa95** [facontidavide/PlotJuggler#189]
I am currently using Version 2.3.0 and I am having trouble adding a prefix (append data) to my current plots. The Data Loader does not give me an option to add prefix as older versions of plot juggler would. 
![image](https://user-images.githubusercontent.com/31670663/62483878-c6c7e300-b786-11e9-854c-a7cd61c8079d.png)

**Comment by facontidavide** [comment]
Hi,

bad news: the feature has been intentionally removed.

good news: you probably don't need it anymore.

In the past the "add prefix" was used to load multiple rosbags at once and avoid overwriting the old timeseries with the same name.

In version 2.3+, you can select multiple rosbags at the same time in the "Open file..." dialog and the prefix will be added automatically.

**Comment by senoa95** [comment]
Awesome! Thank you for promptly answering my question!
