### ISSUE TITLE
Can I begin the streaming from time 0?

### ISSUE THREAD

**Issue by vinbo** [facontidavide/PlotJuggler#192]
when I try to display the topics from ROS, I have to manually pause the gazebo, and then choose topics from plotjuggler, which really took sometime like 2 seconds, and lose the first 2 second's info. How can i begin the streaming from the very beginning? Thanks

**Comment by facontidavide** [comment]
Unfortunately, there is no solution to solve this problem, for the time being.

You an not subscribe to topics that haven't been published yet.

**Comment by facontidavide** [comment]
Since I can not think about anyway to fix this, I am closing the issue. Sorry
