### ISSUE TITLE
Vizualize covariance

### ISSUE THREAD

**Issue by BriceRenaudeau** [facontidavide/PlotJuggler#197]
Recently I can no longer see the covariance matrice when loading odometry data.

Is it hidden somewhere? 

I am using PlotJuggler a lot, thank you, it's great.

**Comment by facontidavide** [comment]
My bad. I removed that data because I thought: "no one is really interested to THAT".

I will fix it.

**Comment by facontidavide** [comment]
Just pushed a fix. have a look 074ff2ac73c44fbe25616e9e23ac2e788a2a61fd
