### ISSUE TITLE
PlotJuggler Installation[Question]

### ISSUE THREAD

**Issue by Marco-Andarcia** [facontidavide/PlotJuggler#2]
I am trying to install the Cmake package by running:

`PlotJuggler$ cmake CMakeLists.txt`

However I am getting the following output: 

```
  CMake Error at CMakeLists.txt:40 (add_subdirectory):
  add_subdirectory given source "qwt/src" which is not an existing directory.
```

Do I need to build something else before I build this? 

Thanks in advance!

**Comment by facontidavide** [comment]
Hi Marco,

since you closed the issue I guess you noticed already that you qwt is a git submodule.
My bad, the documentation is still non existent.
