### ISSUE TITLE
XY plot axis x have incorrect formating

### ISSUE THREAD

**Issue by aeudes** [facontidavide/PlotJuggler#222]
Just to report that when use the XY axis plot feature, the X axis still have a date/time formatting:
this behavior is reproducible with any input data (-t / example.bag).

**Comment by facontidavide** [comment]
I guess you mean, when the date/time button is activated. Nice catch, I will fix it

**Comment by aeudes** [comment]
True, only when date/time is on.
Thanks !

**Comment by facontidavide** [comment]
done. Thanks again for reporting
