### ISSUE TITLE
Now I can buffer data from 0 to 100 second, but I want to buffer data from 0 to endless.

### ISSUE THREAD

**Issue by hongzhifu** [facontidavide/PlotJuggler#229]
Thanks for your work. This software is very convient for me.
Note:
I install the plotjuggler use 'apt-get install', not source code.
The previous version can buffer data with endless time, but new version not.

What should I do next?

**Comment by facontidavide** [comment]
Short answer : there is an option in the command line. Check "--help".

Long answer : that is a very bad idea if you subscribe to large messages, because everything is stored in RAM.

**Comment by autonomobil** [comment]
Same problem here, I want to stream via a ROS Topic Subscriber but  `rosrun plotjuggler plotjuggler --buffer_size 2000` starts plotjuggler with buffersize 100

**Comment by autonomobil** [comment]
Ah but now I can go to 2000 in plotjuggler itself, ok works for me
