### ISSUE TITLE
can not x-y plot by reading the rosbag data

### ISSUE THREAD

**Issue by Allenhanbo** [facontidavide/PlotJuggler#231]
Hi all, recently I installed the ROS version PlotJuggler by using command sudo apt-get install ros-kinetic-plotjuggler. Then I load my rosbag data that I record before and do the plot. 

In this rosbag file: https://drive.google.com/file/d/14Vt4SdR1afJNDsPujfYmVBUT0hm0uVxw/view?usp=sharing

I foucus on three topics which is: /vicon/cf1/cf1/transform/translation/x, /vicon/cf1/cf1/transform/translation/y, /vicon/cf1/cf1/transform/translation/z. 

These are the trajectory components data of my quadrotor. 

I would like to plot x-y together, but I failed. The X-Y plot option is not permited.

Does anyone help me about this problem?

**Comment by facontidavide** [comment]
The way XY plot are created changed in version 2.3.3

https://github.com/facontidavide/PlotJuggler/releases/tag/2.3.3

It works just fine with your data:

![image](https://user-images.githubusercontent.com/2822888/69943796-065ccc80-14e6-11ea-8de9-3cc2eb74bb3d.png)
