### ISSUE TITLE
Can I add reference trajectory?

### ISSUE THREAD

**Issue by Allenhanbo** [facontidavide/PlotJuggler#233]
Hi Davide, thanks for your awesome plot tool, it helps me a lot on research.

I have a question about adding some reference value. We can plot the data we saved in rosbag now. As I know, some guys' data maybe about the robotics moving trajectory, like coordinate x values and y values in move. When we recovery this data into plot, there's another thing we would like to know is about the trajectory accuracy compared with the path we designed.

For a simple case, if we want the robot to move in a circle figure, we can use the x and y value to plot the actual trajectory. Can we add a reference circle into the figure now?

**Comment by facontidavide** [comment]
it is possible, but a little bit "hack-y"

You can create a new timeseries for x and y using the time from your odometry, like this:

[pj-2019-12-04_12.13.00.mkv.tar.gz](https://github.com/facontidavide/PlotJuggler/files/3921501/pj-2019-12-04_12.13.00.mkv.tar.gz)
