### ISSUE TITLE
Data name tab completion

### ISSUE THREAD

**Issue by scott-eddy** [facontidavide/PlotJuggler#24]
It would be great to have the ability to tab complete data for rostopics that have a lot of subfields.

**Comment by facontidavide** [comment]
Usually the search box works pretty well for me. I can easily navigate through in 500+ variables.

I might consider to add a third way to use the search box, n which a prefix (with tab completion) is used.

I honestly find this slower, but it can be done; let me think about it.

**Comment by facontidavide** [comment]
Done!

You have an alternative way to filter the list on the left using the mode "prefix" (visible clicking on the cog icon).

When prefix mode is activated, you will see the autocompletion. Don't use TAB, though, I was not able to make it work
