### ISSUE TITLE
/tmp/.mount_PlotJu2izK5D/AppRun.wrapped: symbol lookup error: /tmp/.mount_PlotJu2izK5D/usr/bin/libDataStreamROS.so: undefined symbol: _ZN16RosIntrospection7ROSTypeC1EN6nonstd7sv_lite17basic_string_viewIcSt11char_traitsIcEEE

### ISSUE THREAD

**Issue by Luminary-S** [facontidavide/PlotJuggler#243]
I am using it in Ubuntu 18.04 melodic ROS.

When I start the plotjuggler with apt install method, the menu of the window seems not to react when I pressed the "streaming", "file"  and other buttons of that line.

So I transfer to download the appimage, everything is ok before I choose the ros topic, but when I choose like "imu_data", and press "ok", the window corrupts and shows the message:

> /tmp/.mount_PlotJu2izK5D/AppRun.wrapped: symbol lookup error: /tmp/.mount_PlotJu2izK5D/usr/bin/libDataStreamROS.so: undefined symbol: _ZN16RosIntrospection7ROSTypeC1EN6nonstd7sv_lite17basic_string_viewIcSt11char_traitsIcEEE

Please help me, Thx!

**Comment by facontidavide** [comment]
duplicated #227 ?
