### ISSUE TITLE
Fails to compile: std::__cxx1::string does not name a type

### ISSUE THREAD

**Issue by ftsell** [facontidavide/PlotJuggler#251]
In https://github.com/facontidavide/PlotJuggler/blob/869b250771153fe43f7062ea16a7c69f75356713/plotter_gui/transforms/lua_custom_function.cpp#L4 you use `std::__cxx1::string` instead of `std::string` which fails to compile on my machine.

In other parts of the application you use `std::string` therefore I assume it is an oversight and not intentional.

**Comment by facontidavide** [comment]
yes, it is a fault of QtCreator :)
