### ISSUE TITLE
RosStream Plugin does not load: DataStreamROS::clockCallback not implemented

### ISSUE THREAD

**Issue by ftsell** [facontidavide/PlotJuggler#254]
Upon startup, PlotJuggler prints the following error message:

```
"libDataStreamROS.so" :  "Cannot load library /opt/ros/melodic/lib/plotjuggler/libDataStreamROS.so: (/opt/ros/melodic/lib/plotjuggler/libDataStreamROS.so: undefined symbol: _ZN13DataStreamROS13clockCallbackERKN5boost10shared_ptrIKN13rosgraph_msgs6Clock_ISaIvEEEEE)"
```

I was able to pinpoint this problem to [datastream_ROS.cpp](https://github.com/facontidavide/PlotJuggler/blob/master/plugins/ROS/DataStreamROS/datastream_ROS.cpp) not implementing https://github.com/facontidavide/PlotJuggler/blob/ffc5e5a35ad0bc878bbe7b89e713e9040f741d29/plugins/ROS/DataStreamROS/datastream_ROS.h#L53

**Comment by facontidavide** [comment]
For some reason, I don't get this error in Kinetic. THANKS for reporting
