### ISSUE TITLE
visualize data as a point series rather than lines

### ISSUE THREAD

**Issue by orsoromeo** [facontidavide/PlotJuggler#255]
Hi and thanks for this wonderful tool! Is there a way to visualize the data as a point series rather than visualizing the lines that connect those points? If not, are you planning to add it as a possible feature?
thanks

**Comment by facontidavide** [comment]
You my friend, are about to explore the wonderful world of plotjuggler.

Take a deep breath and start exploring the UI.

Right click on a plot 😉

**Comment by orsoromeo** [comment]
Beautiful! I love plotjuggler. Sorry for the spam.

**Comment by facontidavide** [comment]
Don't worry, I was just pulling your leg ;)
