### ISSUE TITLE
[Bug] Selecting SVG actually exports a PNG

### ISSUE THREAD

**Issue by CodeFinder2** [facontidavide/PlotJuggler#258]
Thanks for the great tool!

I am using v2.5.0 (ros-melodic-plotjuggler) and tried to export data to an image using [right click on plot] -> "Save plot to file". Selected SVG but the tool actually saved a PNG. :see_no_evil: I was able to solve it by also adding ".svg" as an extension but I think this shouldn't be required when SVG is already selected as type (in the lower right of the export dialog). May be related to #25 
Edit: It may happen that the type is just used as a filter to show existing files of that type (which would still be a bug)? 🙈 

Note: I used a ROS topic for the data but i think this is irrelevant anyway. ;-)

Thanks for taking a look!

**Comment by facontidavide** [comment]
Interesting... I will check that out

**Comment by facontidavide** [comment]
Fixed. Thanks for reporting
