### ISSUE TITLE
show hour:min:second in the x axis

### ISSUE THREAD

**Issue by Xiaodaxia2015** [facontidavide/PlotJuggler#259]
The plotjuggler is an amazing tool in the ROS, I have used it a lot to processing data.
However, I found the X-axis is only shown in relative time (starts from 0), but can't be displayed as an exact time like Hour:min:second. Actually, with the ROS timestamp, we can easily turn it into day:hour:min:second form.
Thank U guys, hoping for the update.

**Comment by facontidavide** [comment]
Something like this?

![image](https://user-images.githubusercontent.com/2822888/76304125-1fce9b00-62c3-11ea-8a81-11e03e89dbcc.png)

**Comment by Xiaodaxia2015** [comment]
Nice！ Wonderful tool
