### ISSUE TITLE
Is it possible to plot poses that are separated without time series?

### ISSUE THREAD

**Issue by kibolho** [facontidavide/PlotJuggler#268]
I have my bag file from a recorded trajectory, i am using "hector_trajectory_server" to get the trajectory. I would like to compare the planning trajectory and the real trajectory.

Thanks in advance!
<img width="1291" alt="Screen Shot 2020-03-28 at 20 44 58" src="https://user-images.githubusercontent.com/1197923/77836457-0471e580-7135-11ea-9079-af87683c2886.png">

**Comment by facontidavide** [comment]
lot, lot of people wants to do this.

Unfortunately the answer is "you can't". This would require a new find of Plugin that generate a timeseries out of the list of points. Or the posibility to load in a XY plot something that is NOT a timeseries :(

Either way it is a bit of a hack. But there are so many people that wants to do that that I guess I must find a way... eventually.

But this will not happen anytime soon.

**Comment by kibolho** [comment]
Hello!
I did a script in Matlab to solve my problem:
https://abilioazevedo.wordpress.com/2020/04/15/plot-trajectory-from-bag-file-using-matlab/
Thanks for answering!
