### ISSUE TITLE
ordering of array messages in left sidebar

### ISSUE THREAD

**Issue by scott-eddy** [facontidavide/PlotJuggler#27]
Currently array messages in the left sidebar are grouped alphabetically, but the case where you have over 10 data fields in a message leads to strange ordering.  E.G. you will have

```
variable_0
variable_1
variable_10
variable_11
...
variable_19
variable_2
variable_20
```

If the variable has the same name the ordering should be based on numbering

**Comment by facontidavide** [comment]
This is one of those use cases where a PR is welcome :)
