### ISSUE TITLE
Can't get custom function to work

### ISSUE THREAD

**Issue by msadowski** [facontidavide/PlotJuggler#271]
Thanks for contributing to PlotJuggler. You are great!!!

- I used version 2.6.2-1 (installed through apt-get for ros-melodic)

- Checked with example.bag from datafiles directory

I was trying to create a very simple custom function as follows:

![image](https://user-images.githubusercontent.com/6543766/78662900-84384680-78d1-11ea-91be-b1bad6a7e8db.png)

However every time I'm trying to apply the transform by right clicking on the plot and selecting Custom... and then selecting Invert from the dropdown:
![image](https://user-images.githubusercontent.com/6543766/78663036-c19cd400-78d1-11ea-8d58-52bc82b7243f.png)

I get the warning:
"Something went wront while creating the following curves. Please check that the transform equation is correct.
"

![image](https://user-images.githubusercontent.com/6543766/78663129-e1cc9300-78d1-11ea-86ac-33faba5beec1.png)

I bet I'm doing something wrong but no matter what I don I can't seem to be able to apply the custom transform. Am I missing something?

**Comment by facontidavide** [comment]
That looks like a bug!!! I will have a look at it. Thanks a lot for reporting

**Comment by facontidavide** [comment]
Fixed. Thanks again

**Comment by msadowski** [comment]
Many thanks!
