### ISSUE TITLE
Starting point  disapper

### ISSUE THREAD

**Issue by liuyf5231** [facontidavide/PlotJuggler#272]
Hi Davide,
why the starting point of the red line disappears? 
![bug](https://user-images.githubusercontent.com/47884441/78963983-ab8a5000-7b2b-11ea-9432-94341ddceeff.png)

**Comment by facontidavide** [comment]
Do you know that template you see in any Github Issue that says "please give me a way to reproduce this issue, otherwise I will not be able to haelp you"?

**Comment by liuyf5231** [comment]
> Do you know that template you see in any Github Issue that says "please give me a way to reproduce this issue, otherwise I will not be able to haelp you"?
sorry, I will reproduce it first.
