### ISSUE TITLE
Feature request: copy plot to clipboard

### ISSUE THREAD

**Issue by msadowski** [facontidavide/PlotJuggler#274]
Hi Davide!

I was thinking that it would be a cool feature to allow copying the plot straight to clipboard instead of saving it to file.

Not sure how useful would this feature be for you or other users but I constantly use a screenshot tool to get the plot to my clipboard, this would definitely smooth out the workflow (at least for me).

Many thanks for your continued work on this project!

**Comment by facontidavide** [comment]
It is probably easy...

https://doc.qt.io/qt-5/qclipboard.html

I will see when I can have a look at this

**Comment by facontidavide** [comment]
![image](https://user-images.githubusercontent.com/2822888/80241784-81c14500-8664-11ea-8c48-0ec637d1707a.png)


Enjoy

**Comment by msadowski** [comment]
That's amazing, Thanks Davide!

**Comment by facontidavide** [comment]
Now I am the one using this feature super often.

I am proud of myself 😂.

Seriously though, thanks for the idea and thanks for supporting PlotJuggler ❤️

**Comment by msadowski** [comment]
You're welcome! Always happy to provide feedback. If you ever run Patreon or something similar to support development of PlotJuggler and BehaviorTrees.CPP then I'll definitely look into some long term support!
