### ISSUE TITLE
install fails for user-based install workspaces

### ISSUE THREAD

**Issue by v4hn** [facontidavide/PlotJuggler#276]
Recently, you started [installing desktop and icon files into the system](https://github.com/facontidavide/PlotJuggler/blob/master/CMakeLists.txt#L154).
In theory that's a nice idea for usability, but in practice this does not work and you break users building your code in install workspaces.
Nobody guarantees the install has permissions to access these locations and usually it doesn't.

**Comment by facontidavide** [comment]
I think this commit should solve the issue: 

e8784fffadf9c6a087d46477b8e56a269de613d1
