### ISSUE TITLE
PlotJuggler-2.6.4-x86_64.AppImage

### ISSUE THREAD

**Issue by ace-at-git** [facontidavide/PlotJuggler#282]
I would like to to use the new features/corrections, unfortunately it seems that the AppImage 2.6.4 is not available (error 404) :-(

**Comment by facontidavide** [comment]
my bad, I am having some issues creating it

**Comment by ndepal** [comment]
Can we get one for 2.7.0 as well? I need that copy to clipboard feature! :smile:

**Comment by facontidavide** [comment]
as I said, having issues with it. Feel free to try yourself https://github.com/BehaviorTree/BehaviorTree.CPP.git

**Comment by facontidavide** [comment]
done
