### ISSUE TITLE
Remove particular timeserie from the plot

### ISSUE THREAD

**Issue by copterspace** [facontidavide/PlotJuggler#287]
Dear Davide, thank you for Plot Juggler, this tool helps me a lot to analyze my data logs.
Still I have question/ improvement request: how can I remove some particular timeseries I added to my plot? In Cheatsheet I see only option to ADD timeseries to the plot. And then I can undo addition of the last timeserie I added with Ctrl+Z.
But is there any option to remove some particular serie I specify from my plot?
The only way I found yet is to build a new plot and add again all series I need...

**Comment by facontidavide** [comment]
Right click on the plot area... self explaining
