### ISSUE TITLE
Support for Apache IoTDB

### ISSUE THREAD

**Issue by giorgiozoppi** [facontidavide/PlotJuggler#292]
Hey Davide,
it would be nice to see how to get data from https://iotdb.apache.org/ They use thrift and they have already an ongoing client, the only thing that it is missing is your interface

**Comment by facontidavide** [comment]
Considering that:

- it is the first time I see this
- I don't need it
- I can only see client interface for Java and python

This is an hard pass, unless someone wants to sponsor this development or contribute directly.

**Comment by facontidavide** [comment]
Not going to happen. If anyone really need this feature, consider sponsorship.
