### ISSUE TITLE
Bug in quaternion_msg.h

### ISSUE THREAD

**Issue by YechenZhou** [facontidavide/PlotJuggler#299]
Thanks for contributing to PlotJuggler.  When I use plotjuggler for IMU to display the attitude curve, I found that the variable `quat_norm2` calculation may be wrong. The line is `double quat_norm2 = q.w * q.w + q.x * q.x * q.y * q.y + q.z * q.z;` in the file PlotJuggler/plugins/ROS/ros1_parsers/quaternion_msg.h. The line probably should be modified to 
`double quat_norm2 = q.w * q.w + q.x * q.x+ q.y * q.y + q.z * q.z;`

**Comment by facontidavide** [comment]
thanks a lot for spotting this. fixed
