### ISSUE TITLE
Question: Plans to support ros2-foxy? 

### ISSUE THREAD

**Issue by alexselwa** [facontidavide/PlotJuggler#307]
Super excited to find PlotJuggler!! 

Apologies for asking this in a GitHub issue but I was curious if anyone is working on support for newer ROS2 distros like Foxy? On first glance there were a few changes that broke the ros2 branch, such as `rmw_message_info_t` to `rclcpp::MessageInfo` (see `subscription_base.hpp` in rclcpp). 

 Thanks for developing this awesome tool!

**Comment by facontidavide** [comment]
That will surely require some work and right now i am focused on other tasks. Any contribution from the community is welcome.

**Comment by facontidavide** [comment]
this is done in theory. Waiting to check #328 before closing this issue too.

**Comment by facontidavide** [comment]
done 

![boom_celebrate](https://user-images.githubusercontent.com/2822888/93509879-a4f4d580-f920-11ea-9d46-2d1169fd1702.gif)

**Comment by alexselwa** [comment]
Amazing, thank you!!
