### ISSUE TITLE
Question: ability to follow cursor position from outside plotjuggler

### ISSUE THREAD

**Issue by orshefi** [facontidavide/PlotJuggler#311]
Hi,

I wondered if there is any option to capture the cursor position (time of record) and send it somehow to an application outside of plotjuggler.

The reason I'm interested in that is to be able to sync video playing with the time series displayed in plotjuggler.

If by chance you have other ideas on how to achieve that I'll be glad to hear as well.

Thanks a lot

**Comment by facontidavide** [comment]
I am glad you ask!

There is an entire class of plugins that are triggered by the cursor: 

https://github.com/facontidavide/PlotJuggler/blob/master/include/PlotJuggler/statepublisher_base.h#L20

The method play() is called synchronouslñy anytime the cursor is updated.

You can implement a trivial plugin that publishes the time to your application.
