### ISSUE TITLE
add tree view in custom time series: source data and curve selector

### ISSUE THREAD

**Issue by improve100** [facontidavide/PlotJuggler#312]
Thank you for the good tools, help me a lot.
There is some requests,may be more handly for using.
when I have a lot of topics to display and i want my custom function. i need to clicked custom time series,then select curve selector and source data.  i need socoll mouse a lot to find my picked. it is boring.

**Comment by facontidavide** [comment]
I am working on a much better interface in PlotJuggler 3.0. Stay tuned ;)

For the time being, remember that if a timeseries is selected BEFORE pushing the "Create custom" button, that will be automatically used
