### ISSUE TITLE
Feature request: Different line styles

### ISSUE THREAD

**Issue by peci1** [facontidavide/PlotJuggler#33]
Having the possibility to plot dotted/dashed lines would be useful.

**Comment by facontidavide** [comment]
You can already display lines + dots (right click in the plot area to see the option).
Being honest, I am trying hard to reduce the amount of options that the user interface offers to keep it as simple as possible, and the customization of the curve is not one of my priorities.

**Comment by facontidavide** [comment]
I will unlikely do this. closing the stalled issue
