### ISSUE TITLE
scatterplots

### ISSUE THREAD

**Issue by soldierofhell** [facontidavide/PlotJuggler#331]
Hi @facontidavide,

PlotJuggler is fantastic for time series visualization, but what about [scatter plots](https://en.wikipedia.org/wiki/Scatter_plot)? Is it currently possible to do this kind of plots? In any way, may be hacky or even with code change?
Scatterplots are really helpful with visualizing 2D localization (xy).

Regards,

**Comment by facontidavide** [comment]
If you have one series with X and another with Y, you can combine them in XY.

Drag and drop them with right button of the mouse.

To see it as a scatter plot, right click on the plot and change the line/points mode.
