### ISSUE TITLE
Visual issue in dark mode: Placeholder for filter

### ISSUE THREAD

**Issue by g3n35i5** [facontidavide/PlotJuggler#333]
Just a small visual problem: In dark mode the placeholder for the filter is displayed in black and therefore cannot be recognized easily. As soon as text is entered, the color changes to white.
![Screen Capture_select-area_20200925161747](https://user-images.githubusercontent.com/17593457/94278388-08978800-ff4b-11ea-937a-3027b0457d17.png)
![Screen Capture_select-area_20200925161803](https://user-images.githubusercontent.com/17593457/94278391-09301e80-ff4b-11ea-832b-f840e2caa69a.png)

**Comment by g3n35i5** [comment]
I don't know why but after rebuilding and restarting the application a few times this magically disappeared (for now). Maybe it's just an issue with my environment.

**Comment by facontidavide** [comment]
hi. Thanks for reporting. Right now I am focused on PlotJuggler 3.0 and the new dark filter there. I will keep this in mind.
