### ISSUE TITLE
Question: How to group values in the variable explorer

### ISSUE THREAD

**Issue by g3n35i5** [facontidavide/PlotJuggler#337]
I would like to know if and if yes how it is possible to group array values (e.g. a server responds with an array of values for a variable) in the variable explorer like so:

```
MyVariable
  | 0
  | 1
  | 2
  | 3
  | ...
```

or even better

```
MyVariable
 |  namedValue1
 |  namedValue2
 |  namedValue3
 |  namedValue4
   ...
```

so that i can expand and collapse them.

Currently, I'm adding my variables to the plot like this:

```c++
void MyClass::registerToDataMap(PlotDataMapRef& map) const
{
  if (this->isArray())
  {
    for (size_t i = 0; i < this->arrayLength_; i++)
    {
      map.addNumeric(this->getName() + "[" + std::to_string(i) + "]");
    }
  }
  else
  {
    map.addNumeric(this->getName());
  }
}
```

which results in this:
![Screen Capture_select-area_20201002115350](https://user-images.githubusercontent.com/17593457/94911151-003cd100-04a6-11eb-8832-5a8d04e3a39d.png)

In addition, it'd be great if they could be added to the plot "all together" by pulling the parent node in the variable explorer into the plotting area.

**Comment by facontidavide** [comment]
The hierarchy in the tree is automatically created by the character "/"

**Comment by g3n35i5** [comment]
Thank you very much! Did I miss a section in the documentation or is this behavior not documented?

**Comment by facontidavide** [comment]
I think 🤔 it is ironic since I have zero documentation about hot to create plugins😝

**Comment by g3n35i5** [comment]
Nice one :D Okay thanks!
