### ISSUE TITLE
"Compatible formats" save dialog option unclear

### ISSUE THREAD

**Issue by peci1** [facontidavide/PlotJuggler#34]
At least on my Ubuntu, the "save plot to file" dialog suggests it can save the plot as "Compatible formats", but there is no listing of what formats are compatible. There is also no warning/error message when you give the file an unsupported extension.

![snimek obrazovky porizeny 2017-03-28 15 14 01](https://cloud.githubusercontent.com/assets/182533/24406766/426bb78e-13c9-11e7-902b-ea43c3eb8d52.png)

**Comment by facontidavide** [comment]
Hi,

which version are you using? head of master? 
On my computer It does visualize the alternatives (jpg/png/etc)

**Comment by peci1** [comment]
I'm on git master.

**Comment by facontidavide** [comment]
I can not reproduce it. I believe that if you just click on Compatible Format with the mouse, the full sting should become visible.

Futhermore, I am following the suggestions of the original documentation. http://doc.qt.io/qt-5/qfiledialog.html#setNameFilter
