### ISSUE TITLE
Typo in error message "cannot is not"

### ISSUE THREAD

**Issue by bengt-ehn** [facontidavide/PlotJuggler#343]
There is a typo or incomplete error message in [datastream_ROS.cpp::DataStreamROS::timerCallback()](https://github.com/facontidavide/PlotJuggler/blob/c9c650b9254df9c637cf5a8b007bcc65a6c10be9/plugins/ROS/DataStreamROS/datastream_ROS.cpp): 

"The roscore master **cannot is not** reachable anymore.\n\n"

I suggest to remove the word "cannot" unless the meaning was to tell something else.

**Comment by facontidavide** [comment]
Fixed in plotjuggler 3. Thanks
