### ISSUE TITLE
plot dataA vs dataB instead of dataA vs time

### ISSUE THREAD

**Issue by jhabhargav26** [facontidavide/PlotJuggler#35]
Hi! 
I want to plot real time trajectories of my robots using this. I am getting data as Pose2d message. Is it possible to plot X-coordinate vs Y-coordinate on a plot? Right now I can only plot as time series.

Thanks,
Bhargav

**Comment by facontidavide** [comment]
it is!

Drag and drop a curve with the RIGHT mouse and it will become the X coordinate.

**Comment by jhabhargav26** [comment]
thanks :)
