### ISSUE TITLE
Installation via apt for ROS foxy not working

### ISSUE THREAD

**Issue by agutenkunst** [facontidavide/PlotJuggler#351]
Maybe this is related to https://github.com/facontidavide/PlotJuggler/issues/345

I'm running foxy on Ubuntu 20.

Trying to install PlotJuggler using `sudo apt-get install ros-foxy-plotjuggler`
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ros-foxy-plotjuggler
```

I did `apt-get update` etc... Looking at https://github.com/ros/rosdistro/blob/cf5d85461c27941643a1cf88620e44d3d00811f0/foxy/distribution.yaml#L2088 it should work.

I can install `ros-foxy-plotjuggler-msgs` which is at 0.1.2-1

**Comment by facontidavide** [comment]
Hopefully it should be fixed tomorrow

https://discourse.ros.org/t/preparing-for-foxy-sync-and-patch-release-2020-12-11/17804
