### ISSUE TITLE
libqt5multimedia5-plugins cannot be authenticated

### ISSUE THREAD

**Issue by caioaamaral** [facontidavide/PlotJuggler#352]
While installing plotjuggler (currently running at ros kinetic environment) apt  warns me:

```
WARNING: The following packages cannot be authenticated!
  libqt5multimedia5-plugins
```

Is that desired?

**Comment by facontidavide** [comment]
Nope.

PlotJuggler 3 does not need that library, on the other hand I am not planning to release version 3 for kinetic.

I am not sure I can/will provide any solution to this issue.
