### ISSUE TITLE
Cannot install on melodic due to conflicting packages

### ISSUE THREAD

**Issue by jcmonteiro** [facontidavide/PlotJuggler#354]
Hi Davide,

I know that this issue is not exactly PlotJuggler's fault, but when installing the package it attempts to place the `MQTT*.h` headers from the 3rd party library https://github.com/eclipse/paho.mqtt.c in the root `/opt/ros/melodic/include` directory. In my use case, they conflict with another library that is using MQTT exactly like PlotJuggler - as a 3rd party package compiled from source.

A solution would be to edit the `CMakeLists` file and change the installation path, or have `libmosquittopp-dev` as a dependency for PlotJuggler instead of compiling from source.

What do you think?

**Comment by facontidavide** [comment]
Ok, I will fix that ASAP, the truth is that we don't really need to install that at all.

Thanks for reporting

**Comment by facontidavide** [comment]
should be fixed
