### ISSUE TITLE
desktop file didn't specify exec field

### ISSUE THREAD

**Issue by deepcoder** [facontidavide/PlotJuggler#373]
Following your recommended install method on Ubuntu 20.04, when trying to launch app from Launcher, you get:

```
desktop file didn't specify exec field
```
resolved by editing file:
```
sudo vi /var/lib/snapd/desktop/applications/plotjuggler_PlotJuggler3.desktop
```
and adding line:
```
Exec=/snap/bin/plotjuggler
```

**Comment by facontidavide** [comment]
Thanks a lot for reporting. Fixed here: https://github.com/PlotJuggler/plotjuggler3_snap/commit/367d4008dac5f34d4d476c8a92b9aaae89912701
