### ISSUE TITLE
ROS subscriber, problem with varying size arrays.

### ISSUE THREAD

**Issue by ozzdemir** [facontidavide/PlotJuggler#374]
When visualizing elements of arrays with varying size, pj cannot receive values from the topic that publishes as an array with varying size. I added a video that shows the problem and a bag file to reproduce it.
https://user-images.githubusercontent.com/30624975/103084160-6772a900-45ef-11eb-96e2-246be5888346.mp4

[pj-test-varying-size-problem_bag.zip](https://github.com/facontidavide/PlotJuggler/files/5739334/pj-test-varying-size-problem_bag.zip)

**Comment by facontidavide** [comment]
You forgot this variable. 

![Selection_038](https://user-images.githubusercontent.com/2822888/103089282-d7802f80-45ed-11eb-912b-288d9e2d418d.png)

**Comment by ozzdemir** [comment]
It was so obvious :sweat_smile:, thanks for reminding.
