### ISSUE TITLE
Import CSV file fails if a column header has a comma. Ex: "Torque, Request"

### ISSUE THREAD

**Issue by Godjka** [facontidavide/PlotJuggler#378]
Hi!

I am using PlotJuggler as a visualization tool for some CSV data. I noticed that if I have a comma between a header name, ex: "Torque, Request", PlotJuggler breaks it down into 2 columns, and because of that it fails to import the data. No warning/message is displayed, and the Timeseries list is empty. I upload a simplified dummy data.

The work around is to remove the comma in the header names, but would like to either PlotJuggler display an error saying that it failed to import the data or to be able to handle when the header has a comma.

[DummyData.csv.zip](https://github.com/facontidavide/PlotJuggler/files/5751452/DummyData.csv.zip)

This happens in the most recent version of PlotJuggler.

Thank you!

**Comment by facontidavide** [comment]
Let's play "bad cop, good cop" :smiling_imp: 

**Bad cop**: "are you complaining that adding arbitrary commas to a format that is literary called **Comma Separated Value** is misleading?

**Good cop**: I added a more informative warning message.

Cheers :smile:
