### ISSUE TITLE
Time/Distance measurement

### ISSUE THREAD

**Issue by g3n35i5** [facontidavide/PlotJuggler#388]
Hi again! So far, i love the 3.X version of PlotJuggler, great work!

I have a small feature request (If its already implemented and i cant find it: please blame me publicly :smile:)

It would be great if you could measure distances in the X/Y plane (delta of time, delta of curve, ...). I would imagine a kind of "ruler" as a implementation.

![Selection_023](https://user-images.githubusercontent.com/17593457/104903980-f7064000-5980-11eb-9853-464fb2c10ce7.png)

**Comment by facontidavide** [comment]
No, unfortunately there isn't such a feature. It seems very specific and I doubt that I will work on this any time soon, sorry.

**Comment by g3n35i5** [comment]
All right, it was worth a try :D Thanks for the quick reply!
