### ISSUE TITLE
Color/Palette issue on Windows

### ISSUE THREAD

**Issue by JimmyDaSilva** [facontidavide/PlotJuggler#390]
Hi Davide,

I know there is no Windows release yet, but I wanted to use it now anyway...
I built the last version(https://github.com/facontidavide/PlotJuggler/commit/6dc10a385591bc097b2b69e4367cbfa3ffe06d59) of PlotJuggler from source with QT 5.15.2 and MSVC 2017. 
I got it to compile and run.

But there is a weird color issue. Can't say where it comes from.
Light theme:
![image](https://user-images.githubusercontent.com/5452370/105059347-783ffe80-5a77-11eb-8350-a04a510effd2.png)

Dark theme:
![image](https://user-images.githubusercontent.com/5452370/105059308-6cecd300-5a77-11eb-8573-13ce51a489dd.png)

**Comment by facontidavide** [comment]
well, that looks really bad :( 

I need to have a look at this

**Comment by facontidavide** [comment]
fixed. Thanks a lot!
