### ISSUE TITLE
[Feature Request] Option to scale XY graphs by the series on each axis instead of using aspect ratio and the larger range

### ISSUE THREAD

**Issue by jlmcmchl** [facontidavide/PlotJuggler#395]
Working off commit #89f9ac8f97f2bdb27a486c57b1d9fd39a55d4078

I certainly understand the desire to have XY graphs scaled equally on both axes - if you want to graph position on a plane the best visual is for x and y to be scaled equally. However, there are use cases where I'd like to use a different index series than the chosen one for a graph, a good example being a motor model in a simulation, where the x axis is commonly velocity, and the y axis is one of many other properties, and not all of them share the same scale as velocity.

How to reproduce:

- Load motor data from this gist: https://gist.github.com/jlmcmchl/1f69002aad28f3a324e96c6c797fceb7

- Create a pair of custom timeseries:
  - `power`, calculated from `Velocity` * `Force to Carpet`
  - `velocity`, which just returns the value from `Velocity`
- Create an XY graph with either series on X, and either series on y. Example w/ `velocity` on x and `power` on y: 
![image](https://user-images.githubusercontent.com/1332080/106086347-f9d70280-60ef-11eb-8cfd-46f8ef008806.png)

- Desired result should be something closer to this (using `Motor Speed` on the x axis): 
![image](https://user-images.githubusercontent.com/1332080/106086327-f04d9a80-60ef-11eb-9b5e-a8cb9cee697e.png)

**Comment by facontidavide** [comment]
I am trying to avoid "feature creep". 

Anyway, I just disable the 1:1 and it works just fine:

![Selection_029](https://user-images.githubusercontent.com/2822888/106381672-ba900680-63ba-11eb-82cb-f60e46ec79a8.png)
