### ISSUE TITLE
Compilation issue (Ubuntu 18.04, ROS Melodic)

### ISSUE THREAD

**Issue by mtlazaro** [facontidavide/PlotJuggler#397]
Hi,

First of all thanks for sharing this awesome tool, we are using it a lot to analyse data from our bags.

However we recently tried to compile from source in a new laptop and it is not compiling anymore. 
It gives a Qt error on:
datastream_zmq.cpp
related to some late changes on Qt objects:
...../PlotJuggler/plugins/DataStreamZMQ/datastream_zmq.cpp:89:13: error: declaration of ‘QString protocol’ shadows a parameter
     QString protocol = dialog->ui->comboBoxProtocol->itemText(index);
...../PlotJuggler/plugins/DataStreamZMQ/datastream_zmq.cpp:89:68: error: no matching function for call to ‘QComboBox::itemText(<unresolved overloaded function type>)’
     QString protocol = dialog->ui->comboBoxProtocol->itemText(index);
and some more in the same file...

If we clone commit 1020fbb9ea68af65ec970358d973fcee086d4375 the error does not appear and the code compiles correctly.

Hope you can fix it so we can clone the latest version.
Best,

**Comment by facontidavide** [comment]
fixed!
