### ISSUE TITLE
Cannot start PlotJuggler under ROS2.

### ISSUE THREAD

**Issue by whatis777** [facontidavide/PlotJuggler#399]
### Use Case
I'd like to start PlotJuggler with ROS2 - unfortunately I cannot get it running nor can I find related informations on the internet for the issue here

### Environment
* common [ROS2 Foxy installation](https://index.ros.org/doc/ros2/Installation/Foxy/Linux-Install-Debians/ ) on Ubuntu Desktop 20.04.1 LTS
* installation of PlotJuggler for ROS2 following this [github tutorial](https://github.com/facontidavide/PlotJuggler#note-for-ros-users)

### The Issue
The [github tutorial](https://github.com/facontidavide/PlotJuggler#note-for-ros-users) contains ROS1 instructions, so I cannot use 
`roslaunch plotjuggler_ros plotjuggler.launch` 
For ROS2 it would be
`ros2 launch plotjuggler_ros plotjuggler.launch`, but then the shell says:

`file 'plotjuggler.launch' was not found in the share directory of package 'plotjuggler_ros' which is at '/opt/ros/foxy/share/plotjuggler_ros'`

### Question

Could you please provide more detailed information in the README how to start plotjuggler_ros for ROS2?

Thanks in advance :-)

**Comment by cshastry** [comment]
I think this is related to issue #398

**Comment by whatis777** [comment]
A question to the community: has anyone experience using PlotJuggler with ROS2? Does it work in general?

**Comment by facontidavide** [comment]
It should work well in Foxy. I am not maintaining older ROS2 versions

**Comment by facontidavide** [comment]
I added a fix that will be available in the next release.

In the meantime, use, for ROS1:

      rosrun plotjuggler plotjuggler

and for ROS2:

       ros2 run plotjuggler plotjuggler
