### ISSUE TITLE
JSON from files

### ISSUE THREAD

**Issue by asherikov** [facontidavide/PlotJuggler#400]
Hello, 
it appears that JSON (CBOR, BSON, Message Pack) support is provided for streams only, I wonder how difficult it would be to implement loading from files. Would it require any architectural changes?

**Comment by facontidavide** [comment]
Not at all, it is just a new plugin. Not in my TODO list for the time being

**Comment by asherikov** [comment]
Welp, the stream parsers assume that the messages are fed separately one by one, it would be necessary to write a type specific file parser to separate messages in the input file. In the end it seems to be easier to stream the messages to plotjuggler with some scripts.
