### ISSUE TITLE
Exception from the ULog plugin

### ISSUE THREAD

**Issue by banuc** [facontidavide/PlotJuggler#405]
PloJuggler gave this error with .ulg file,

The plugin [DataLoad ULog] thrown the following exception:

ULog: error laoding definitions

Dou you have any suggestions?

**Comment by copterspace** [comment]
David, this was reported and repaired already here: https://github.com/facontidavide/PlotJuggler/issues/170.
But now - same issue in  3.1.0 release...

**Comment by facontidavide** [comment]
It can not be the same error, it is probably something else

**Comment by banuc** [comment]
Yes btw im trying with 3.1.0 release.  I am able to upload .csv files but there is a problem with .ulg files.

**Comment by facontidavide** [comment]
send me the incriminated file

**Comment by copterspace** [comment]
For small example:
[log_29_2021-2-15-16-10-42.zip](https://github.com/facontidavide/PlotJuggler/files/6035207/log_29_2021-2-15-16-10-42.zip)

**Comment by jphKelluu** [comment]
Hi. FYI same issue for me with .ulg file on plotJuggler 3.1 windows 10, but same .ulg file loads with plotJuggler 2.8.4.  Thanks for the great tool Davide!

**Comment by facontidavide** [comment]
![image](https://user-images.githubusercontent.com/2822888/108988344-a6c38180-7694-11eb-9f6e-5ba7a84a74eb.png)

Looks good to me... are you experiencing issues on Windows?

**Comment by copterspace** [comment]
Yes, on Windows 10 I get this:
![изображение](https://user-images.githubusercontent.com/38784273/108989450-09297b80-76af-11eb-8d1e-c7e0d6d86cb4.png)

**Comment by banuc** [comment]
I also tried to upload with release 2.8.4 but i'm getting same error in windows 10.


[log_17_2021-1-29-17-36-16.zip](https://github.com/facontidavide/PlotJuggler/files/6041525/log_17_2021-1-29-17-36-16.zip)

**Comment by facontidavide** [comment]
I will try to find some time during the weekend. But please keep in mind that maintaining the ULOG plugin is NOT even at the bottom of my TODO list.

**Comment by facontidavide** [comment]
fixed

**Comment by copterspace** [comment]
Installed recent https://github.com/facontidavide/PlotJuggler/releases/tag/3.1.1 - no change, same error...

**Comment by jphKelluu** [comment]
following up on this issue, for me (windows10), Ulog data files now open in 3.1.1 with no problems! let the memes continue :)

**Comment by facontidavide** [comment]
@copterspace , please provide the ulog file to reproduce the issue

**Comment by copterspace** [comment]
Oh, guess I've found the reason:
In 3.1.1 the error  appeares, when I try to open the file from directory named: "C:\Users\ipetrov.BYTE-1C\Documents\QGroundControl\Logs\Альтитрал3\Полёты с гипером 2"
When I put the same file to "C:\Users\ipetrov.BYTE-1C\Documents\QGroundControl\Logs\" - it opens like a charm :)

In the same folder - once I rename it with Cyrylic symbols - the error appeares. Once I rename folder back with Latin symbols - file from this folder opens like a charm again. 
I had similar troubles with Opencv imwrite() function...

So problem seems to be in Cyrylic path interpretation on Windows.
Not sure you have time and wish to debug this. 
But this workaround might be mentioned in documentation...

**Comment by facontidavide** [comment]
Fixed
