### ISSUE TITLE
Message filter (timeseries list) options and modifiers

### ISSUE THREAD

**Issue by zrsmithson** [facontidavide/PlotJuggler#408]
Built main branch from source on Ubuntu 18.04:

I'm not sure if this is a feature request or just a documentation request, but is it possible to filter timeseries data using search modifiers (AND, OR, *, etc.). In [another issue](https://github.com/facontidavide/PlotJuggler/issues/167) you mention using the "contains" filter options, but I don't see any way to select an option, nor was I able to use any standard/intuitive text modifiers or regex.

Side note, is there any documentation on plutjuggler other than the cheatsheet in the help menu? I can't help but feel there are ways to interface with it or present my visualizations that I am not aware of.

**Comment by facontidavide** [comment]
nope
