### ISSUE TITLE
UDP server only binds to QHostAddress::LocalHost

### ISSUE THREAD

**Issue by jast1982** [facontidavide/PlotJuggler#410]
Hi!

Plotjuggler is a really great tool! Thank you for all the hard work!

I have a simpel and minor issue: My UDP data stream is coming from an embedded system in the same network, but PlotJuggler binds to the UDP-Port with "QHostAddress::LocalHost" instead of "QHostAddress::Any". I am wondering if this is intentional, because it therefore it can't stream from UDP-sources in the same local network. The WebSocket-Streamer binds to "Any", but UDP is just so much simpler on the embedded system ;-)

If it's not intentional, could it be changed in some future version?

Thanks!
Jan

**Comment by facontidavide** [comment]
sure, I will

**Comment by facontidavide** [comment]
done
