### ISSUE TITLE
PlotJuggler missing messages when live streaming

### ISSUE THREAD

**Issue by JoshuaRiddell** [facontidavide/PlotJuggler#411]
When streaming data from ROS, PlotJuggler seems to miss a message approximately every 1.3 seconds. The messages are a custom type sent at about 200Hz. I have a relatively new Xeon laptop so I don't expect it to be due to CPU load.

**Steps to reproduce:**
- unzip data file
- replay data file using "rosbag play plotjuggler_missing_message_test"
- connect plotjuggler to ROS and stream all messages
- output should look like the left screenshot
- to verify all messages are present in the bag file, the bag can be directly opened in PlotJuggler, it should look like the screenshot on the right

**Versions:**
Ubuntu 20.04 Desktop
ROS Noetic (apt install)
PlotJuggler 3.0.7 (snap install)

Thank you for your work on PlotJuggler. It's such an awesome tool and I love using it.

![image](https://user-images.githubusercontent.com/8756194/108935585-b72a2b00-7699-11eb-8a27-cc7bfde7ac56.png)

[plotjuggler_missing_message_test.zip](https://github.com/facontidavide/PlotJuggler/files/6032891/plotjuggler_missing_message_test.zip)

**Comment by facontidavide** [comment]
No, it is not a plotjuggler problem, your data has that spikes.

This was taken looking at the rosbag and using the timestamp in Header

![image](https://user-images.githubusercontent.com/2822888/109385422-feabf380-78f3-11eb-8fa0-268b19da8556.png)

**Comment by facontidavide** [comment]
If you think I am wrong, export the rosbag to csv and shgow me that the spikes are not there  ;)
