### ISSUE TITLE
ULog: error loading definitions

### ISSUE THREAD

**Issue by mengchaoheng** [facontidavide/PlotJuggler#412]
After the Motor Data in the File window, the following prompt appears：

![image](https://user-images.githubusercontent.com/43166007/109595257-1f23ba00-7b4f-11eb-9d39-2e7e59741c5a.png)

**Comment by mengchaoheng** [comment]
I have a px4 log file named log_2_2021-3-1-16-29-42.ulg and I want to view the data

**Comment by mehmetyldz87** [comment]
Same problem 

File: PX4 [ULG File ]
![Error](https://user-images.githubusercontent.com/7778498/109602598-79ae1d80-7b31-11eb-88ac-b0c7c662a0d3.PNG)

Version: 3.1.0 
OS: Windows 10

**Comment by bduva002** [comment]
I am also having an issue running 3.1 on win 10 with a ulog, mine just says not responding though.

**Comment by facontidavide** [comment]
Please try version 3.1.1 and if the problem persist share the ulog file **as I ask every single time in any single issue**.

**Comment by facontidavide** [comment]
Closed. Feel free to reopen once you can provide a way to reproduce (with a FILE)   with version 3.1.1.
