### ISSUE TITLE
Resize and new tab buttons overlap

### ISSUE THREAD

**Issue by Georacer** [facontidavide/PlotJuggler#415]
Hi there! Thanks a million for making PlotJuggler!

Here's a bug report for your troubles :P

Version: 3.0.7 from Snap store.

Issue: When top bar is full with tabs, the "new tab" button overlaps with the "Zoom all" button, making them hard to click.

Cheers!

P.S. If you could repackage releases in to .AppImages it would be great! Snap Store lags a bit behind releases.

**Comment by facontidavide** [comment]
Hi,

Unfortunately when I work with Snaps instead of native builds, I do have problem like this that I have no idea how to address.
I spend a LOT of time to make AppImage work but eventually I had to give up.

Can you send me a screenshot?

**Comment by Georacer** [comment]
![image](https://user-images.githubusercontent.com/3149996/113339433-bc2e6a00-932a-11eb-996f-a530eccd571b.png)

I'm not opposed to building it myself, but some sort of packaging helps convince more people to use it tremendously. A private package repository would works just as well, providing a .deb package.

**Comment by Georacer** [comment]
I have compiled from source in Ubuntu 20.04 and I have the same issue:
![image](https://user-images.githubusercontent.com/3149996/113393010-54156d80-9396-11eb-8da6-6e179d8567bd.png)
