### ISSUE TITLE
Custom function: am I doing it wrong?

### ISSUE THREAD

**Issue by JStech** [facontidavide/PlotJuggler#423]
I'm trying to implement a simple custom function, but it's not working. The pop-up when I mouseover the red circle says "- The Lua function can not compute the result." This is using `ros-melodic-plotjuggler` on Ubuntu 18.04.

![atan2](https://user-images.githubusercontent.com/519268/115129358-5a186a80-9fa2-11eb-8093-92ea66c5b103.png)

Thanks for the help, and for the great software!

**Comment by facontidavide** [comment]
https://www.lua.org/manual/5.3/manual.html

> The following functions were deprecated in the mathematical library: atan2, cosh, sinh, tanh, pow, frexp, and ldexp. You can replace math.pow(x,y) with x^y; you can replace math.atan2 with math.atan, which now accepts one or two arguments.

Therefore, Just rewrite as:

      return math.atan( value, v1)
