### ISSUE TITLE
Cannot select custom messages in Ros 2

### ISSUE THREAD

**Issue by athanasios-riact** [facontidavide/PlotJuggler#425]
Hello there!
Thank you for creating PlotJuggler. I have a question about an error I get.
I have created a custom message to read the TCP force of a UR5 robot.
But when I go to Select ROS messages menu, and select the topic (of datatype **ur_msgs/msg/TcpForce** in this case), I get the following error: **package 'ur_msgs' not found, searching [/opt/ros/foxy]**
I tried importing a plugin folder (the path to the **ur_msgs** package)  in Preferences, restarted PlotJuggler but I still get the error.
 
So am I on the right track? Right now it is only accepting standard ROS messages as the path is set to foxy.
I installed PlotJuggler for ROS2 foxy and sourced the workspace before launching it.
Thank you in advance for the help.

**Comment by facontidavide** [comment]
Please check that the command:

     ros2 topic echo /ur_msgs/msg/TcpForce

Works as expected, than launch PJ in the same console. PlotJuggler should work too.
