### ISSUE TITLE
Feature request full screen mode

### ISSUE THREAD

**Issue by v-lopez** [facontidavide/PlotJuggler#43]
Again awesome tool.

A nice to have feature would be to be able to remove most of GUI elements when my plot has been configured set.

Sometimes I would like to have a plot on a corner of my screen so I can work on other stuff while I am monitoring it.

My best approach was to create a new window for the plot, but even with that I'd say 40% or more of the screen space is used by widgets that at this moment are not needed.

My best approach is this:
![image](https://cloud.githubusercontent.com/assets/3469405/26310509/4327211e-3f01-11e7-8bfa-a882f7b9c108.png)

I wish we could have something like this:
![image](https://cloud.githubusercontent.com/assets/3469405/26310598/a0e6679c-3f01-11e7-9335-f94b576f6a1a.png)

It's a minor feature, and if noone has done it by then, I will try to do it in july when I'll have more free time.

**Comment by facontidavide** [comment]
I will keep it in mind. But I probably I will not start working on this feature anytime soon.

**Comment by facontidavide** [comment]
F10 !!! let me know if it works OK for you
