### ISSUE TITLE
Forward slash in CSV column name results in child items in Timeseries list

### ISSUE THREAD

**Issue by seanmcleod** [facontidavide/PlotJuggler#431]
Column names in CSV files often include the units as part of the column name and so they often have forward slashes, e.g. **Vertical Speed (ft/min)**.

Which then results in the following in the **Timeseries List**.

![image](https://user-images.githubusercontent.com/824856/117552555-5da48c00-b04c-11eb-9876-6e0e77bf18a4.png)

Which is a bit messy visually, but also results in more work when trying to drag that particular column onto the graph, since you first have to expand it and then drag the child item **min** in this example onto the graph.

**Comment by facontidavide** [comment]
This is a built in characteristic of PlotJuggler.

I guess the best option would be to change the separator character in the preference menu.

**Comment by seanmcleod** [comment]
If I open **App -> Preferences...** I don't see any mention of a **separator character** option in either tab. I'm running version 3.1 from the Windows installer link from Readme.md.

![image](https://user-images.githubusercontent.com/824856/117628234-35ff1200-b179-11eb-875a-35dbdddbe4b7.png)

**Comment by facontidavide** [comment]
yes, I know. What I meant is that this option need to be developed, because I don't have it yet.

**Comment by seanmcleod** [comment]
Ah, okay got it. I thought you were referring to an an existing option in the current preferences dialog.

**Comment by seanmcleod** [comment]
I assumed the forward slash separator was designed specifically for data in a hierarchical format, e.g. json encoded data etc. and so shouldn't be applied for CSV data.

**Comment by facontidavide** [comment]
I introduced a quick solution, that is to disable entirely the tree view and the "/" separator.
