### ISSUE TITLE
[rosbag] mavros TimesyncStatus.msg throws exception while loading

### ISSUE THREAD

**Issue by tkazik** [facontidavide/PlotJuggler#432]
First of all: Thx for your great work (and all the memes)!
I am running in the following issue: While loading [this](https://github.com/facontidavide/PlotJuggler/files/6452289/only_battery_and_timesync.zip) example bag, the following exception is thrown.

![plotjuggler_exception](https://user-images.githubusercontent.com/15689124/117665178-dcabd880-b1a2-11eb-8786-fe9b8e11ef4b.png)

The [TimesyncStatus](https://github.com/mavlink/mavros/blob/master/mavros_msgs/msg/TimesyncStatus.msg) message seems to be causing issues.

Any ideas? Keep up the good work!

PS: I also checked out the latest branch (v3.2) and this throws the following seg fault:
```shell
        148:       {
        149:         // Be race-detector-friendly.  For more info see bits/c++config.
        150:         _GLIBCXX_SYNCHRONIZATION_HAPPENS_BEFORE(&_M_use_count);
      > 151: 	if (__gnu_cxx::__exchange_and_add_dispatch(&_M_use_count, -1) == 1)
        152: 	  {
        153:             _GLIBCXX_SYNCHRONIZATION_HAPPENS_AFTER(&_M_use_count);
        154: 	    _M_dispose();
Segmentation fault (Address not mapped to object [0x20])
Segmentation fault (core dumped)
```

**Comment by facontidavide** [comment]
![image](https://user-images.githubusercontent.com/2822888/117713959-94a6a900-b1d6-11eb-9b4e-63cbba68c8e3.png)


It works for me...

The error you are seeing comes from here: https://github.com/PlotJuggler/plotjuggler-ros-plugins

The issue has been fixed here: https://github.com/PlotJuggler/plotjuggler-ros-plugins/commit/9f289f6ca9b7f90eabae1798f58e718f9c157513

I will release a new version. For the time being, you can recompile from source as described in the README
