### ISSUE TITLE
plots seem a bit glitchy with repeated lines using ros noetic

### ISSUE THREAD

**Issue by qiuyuchen14** [facontidavide/PlotJuggler#435]
Hi, 

Thanks for this awesome plotting tool! I'm trying to use plotjuggler with ROS noetic (in VM), and saw something pretty weird: I could see repeated lines, and it seems that the old curves are not removed. The background color in each plot is also dark for some reason. I tried changing the buffer size but it didn't help. It would be great if you can point us where it might  be the issue! Thanks!

![plot_debug1](https://user-images.githubusercontent.com/9788619/117872319-63b88980-b253-11eb-9b12-d586c78f9d19.png)

**Comment by facontidavide** [comment]
I have just pushed a change in the main branch to disable opengl in app->preferences.

Can you try that?

**Comment by facontidavide** [comment]
I REALLY want to help you, but unless I find a way to reproduce this, I can not.

Which VM are you using? Is the host Windows or Linux?

**Comment by qiuyuchen14** [comment]
Thanks so much for investigating this! I emailed you the VM I'm using with details. My host machine is Ubuntu18 with Intel® UHD Graphics 620 (Kabylake GT2).

**Comment by facontidavide** [comment]
FIXED. It was indeed the OpenGL issue! Now the change in preferences should persist.

I will try to release a new version soon-ish, but for the time being, you need to compile both plotjuggler and plotjuggler-ros from source, as explained here https://github.com/PlotJuggler/plotjuggler-ros-plugins

**Comment by qiuyuchen14** [comment]
Thank you so much!!! Yes, it's working now!!!
