### ISSUE TITLE
Unable to locate package ros-kinetic-plotjuggler-ros

### ISSUE THREAD

**Issue by sapan-ostic** [facontidavide/PlotJuggler#436]
Thanks for contributing to PlotJuggler. You are great!

# If you ignore these instructions, I will ignore your issue

Please allow me to better understand your problem providing the following information:

- Please use always the master branch or the latest tag, if you can. 

- Check if the problem can be reproduced using the dummy data created by the command line argument "-t" or one of the files in the folder "datasamples".

- If it can't be reproduced with the dummy data, __please__ share the CSV file or the rosbag that can be used to reproduce the problem.

![share the rosbag](https://github.com/facontidavide/PlotJuggler/raw/master/docs/images/show_me_the_rosbag.jpg)

**Comment by facontidavide** [comment]
Because that package does not exist. 

It was introduced with version 3.X and I never bothered to update that for kinetic. Just install the package ros-kinetic-plotjuggler
