### ISSUE TITLE
How to show original timestamps in plot view, not received time.

### ISSUE THREAD

**Issue by Tumiz** [facontidavide/PlotJuggler#445]
Thanks for contributing to PlotJuggler. You are great!

# Problem description
I use UDP to feed plotjuggler data with timestamps. How to show the timestamps on chart's x axis?

# Steps to reproduce (important)
run the following script
```
import socket
import math
import json
from time import sleep

sock = socket.socket(socket.AF_INET, # Internet
                     socket.SOCK_DGRAM) # UDP
time = 0.0

while True:
    sleep(0.05)
    time += 10

    data = {
        "timestamp": time,
        "test_data": {
            "cos": math.cos(time),
            "sin": math.sin(time)
        }
    }
    sock.sendto( json.dumps(data), ("127.0.0.1", 9870) )
```

**Comment by Tumiz** [comment]
![image](https://user-images.githubusercontent.com/7362124/118798970-cc95a680-b8d0-11eb-951b-efa20a05ab48.png)

**Comment by facontidavide** [comment]
Fixed! Thanks for reporting
