### ISSUE TITLE
Crash when clicking on the "gear" icon

### ISSUE THREAD

**Issue by Kupofty** [facontidavide/PlotJuggler#448]
I want to use the new 3.1.1 version of plotjuggler so I installed it with the linux installer from the github repository (the one on the SoftwareStore is still 3.0.7 when I launch it).
I can launch it perfectly but there's nothing in the "Streaming List" (to choose ROS Topics Subscribe) and when I try to click on the gear icon in the "Streaming" the software crashes.

I'm using Ubuntu 18.04

**Comment by facontidavide** [comment]
I removed the Linux installer. Try the AppImage here:

https://github.com/facontidavide/PlotJuggler/releases/tag/3.1.1
