### ISSUE TITLE
value for PI in rad_to_deg function of library?

### ISSUE THREAD

**Issue by ljburtz** [facontidavide/PlotJuggler#461]
Unexpected value for PI in rad_to_deg function of library

![image](https://user-images.githubusercontent.com/26211495/122209921-06fa5f80-cee0-11eb-8883-00620df6978d.png)
PI = 3.14159....so shouldn't the fourth decimal in the equation be a 6 instead of a 7?

Seems like a minor typo!

**Comment by facontidavide** [comment]
it is a minor typo. thanks for noticing
