### ISSUE TITLE
Add option to visualize points instead of lines

### ISSUE THREAD

**Issue by AndyZe** [facontidavide/PlotJuggler#462]
If you're familiar with MATLAB, it has many different plot style options. A lot of times, I plot the individual datapoints rather than interpolated lines. The problem with plotted lines is, we don't know how many datapoints are on the line or exactly where they are.

So it would be great to have a "points" option!

**Comment by facontidavide** [comment]
https://slides.com/davidefaconti/introduction-to-plotjuggler

**Right click ->  Edit curves...**
