### ISSUE TITLE
Y tick labels lose precision when data magnitudes are small

### ISSUE THREAD

**Issue by sjs329** [facontidavide/PlotJuggler#463]
# Problem description

In a recent version update of PlotJuggler (within the last year...) the behavior of Y-axis tick labels seems to have changed. When the magnitude of the data in view is small enough, the significant figures / precision of the labels is no longer enough to be useful. See attached image where the Y axis labels are all zeros. This makes it much harder to tell what's happening with signals that are significant at very small magnitudes.
![image](https://user-images.githubusercontent.com/1324467/122574542-bc7efd00-d01d-11eb-859f-43949b5b1557.png)

# Steps to reproduce (important)

- Describe your platform / Operative System:
  - Ubuntu 18.04, PlotJuggler version 3.2.0, using ROS plugin (though that doesn't seem to be necessary to reproduce)
- CSV file to reproduce: 
[small_magnitude_example_modified.csv](https://github.com/facontidavide/PlotJuggler/files/6677907/small_magnitude_example_modified.csv)

**Comment by facontidavide** [comment]
fixed

**Comment by sjs329** [comment]
Fixed indeed! Thanks @facontidavide !
![image](https://user-images.githubusercontent.com/1324467/122617584-8c098400-d05a-11eb-8622-4decbd9733a2.png)
