### ISSUE TITLE
Bug in timestamp in IMU message header

### ISSUE THREAD

**Issue by hasky67** [facontidavide/PlotJuggler#473]
# Bug in visualisation of nanosecs in timestamp in IMU message

I found out, that there is a bug in visualisation of IMU header timestamp nanosecs, it looks like, that secs and nanosecs is the same. I uploaded 2 printscreen, one with running rosbag, where I have IMU message at 75 Hz, and plotjugler, where it can be seen, that nanosecs and secs in IMU message (does not affect Odometry type message).

# Steps to reproduce (important)

- Ubuntu 20.04 ROS2 Foxy
- I upload the rosbag for reproducing the problem as well, feel free to use it :) 

![Screenshot from 2021-06-29 17-15-55](https://user-images.githubusercontent.com/48917311/123824003-f396bd80-d8fd-11eb-9bc6-ab01ea531bbb.png)
![Screenshot from 2021-06-29 17-16-35](https://user-images.githubusercontent.com/48917311/123824007-f42f5400-d8fd-11eb-80c7-01a475541b6e.png)
[rosbag2_2021_06_29-17_11_49.zip](https://github.com/facontidavide/PlotJuggler/files/6734502/rosbag2_2021_06_29-17_11_49.zip)

**Comment by facontidavide** [comment]
thanks. This error has been fixed already in the newer version (1.5) 

https://github.com/PlotJuggler/plotjuggler-ros-plugins/blob/1.5.0/plugins/ros2_parsers/imu_msg.h
