### ISSUE TITLE
Using PlotJuggler with ZMQ+Protobuf

### ISSUE THREAD

**Issue by junhyeokahn** [facontidavide/PlotJuggler#476]
Hello,

I just have a quick question regarding using this nice PlotJuggler with ZMQ+Protobuf.
I found an example and a tutorial that you publish JSON through ZMQ and plot it online.
However, if I want to publish a customly-serialized protobuf message, how I can parse my protobuf msg?

**Comment by facontidavide** [comment]
This is possible but complicated.

There are two options: 

1. Create a custom plugin that can parse your own Protobuffer  messages.
2. Protobuffer has a "dynamic message" API that can help you parsing generic messages at run-time, this should allow you to create an universal parser and add ptotobuf to the list of recognized protocols.

If anybody wants to contribute with the latter, he/she is welcome to send a PR.

If any company want me to work on option 2., please consider sponsoring this feature.
