### ISSUE TITLE
Import of CSV with semicolon fails

### ISSUE THREAD

**Issue by maracuya-robotics** [facontidavide/PlotJuggler#479]
# Problem description

After updating from 3.1.1 to 3.2.1 (ROS Noetic) CSV files with semicolon as delimiter cannot be loaded anymore. This is a regression from 3.1.1.

# Steps to reproduce (important)

- Download CSV file from #48
- Open in PlotJuggler. In the "Select the time axis" dialog only two items are available: `INDEX (auto-generated)` and the CSV header as a single item `;A;B;C;D`.

**Comment by facontidavide** [comment]
yes, I am aware.

There are technical reasons to do that, in particular to avoid issues with the new plugin that export CSV files.

The solution is to make the delimiter configurable in the GUI.

**Comment by facontidavide** [comment]
done!

![image](https://user-images.githubusercontent.com/2822888/132136050-af088cde-1e43-40e2-b63a-364b029dcdc4.png)
