### ISSUE TITLE
Support common CSV delimiters

### ISSUE THREAD

**Issue by dmiklic** [facontidavide/PlotJuggler#48]
[A `.csv` file using semicolons as delimiters](https://github.com/facontidavide/PlotJuggler/files/1085645/test.txt)
 will not be imported correctly.

This behaviour is with the current master head. As semicolons are quite commonly used delimiters in `.csv` files it would be nice to have support for this.

**Comment by facontidavide** [comment]
is there any other delimiter that you would add a part from semicolon?

**Comment by dmiklic** [comment]
Most of the files I have come across so far use the semicolon. Other delimiters besides comma I have seen occasionally are space, tab, colon and pipe `|`.

**Comment by facontidavide** [comment]
done :)

**Comment by dmiklic** [comment]
Great, thanks! :)
