### ISSUE TITLE
Plotting csv data series doesn't match what is expected.  Y-axis is off

### ISSUE THREAD

**Issue by jmailloux** [facontidavide/PlotJuggler#480]
Thanks for contributing to PlotJuggler. You are great!

# Problem description
Plotting a data series from a csv file.  Something appears wrong with the y-axis.  Everything is shifted.

# Steps to reproduce (important)
- Plot "equivalent_ground_minus_wind_m_s" from attached csv file.
- Expected to get something like what was generated with Octave (attached)
- Got something that seems to be shifted on the y-axis.
- 
- Describe your platform / Operative System. - MacOS Big Sur.  11.4.
- Getting the same result using PlotJuggler -t and plotting _sin
![plotjuggler -t](https://user-images.githubusercontent.com/6007135/124821109-4d216c80-df3c-11eb-8a7f-424eed6fc3aa.png)
![plotjuggler equivalent_ground_minus_wind_m_s](https://user-images.githubusercontent.com/6007135/124821410-ad181300-df3c-11eb-9ae5-563fe811e3f6.png)
[log_35_2021-6-30-17-00-56_airspeed_validated_0.csv](https://github.com/facontidavide/PlotJuggler/files/6779811/log_35_2021-6-30-17-00-56_airspeed_validated_0.csv)

**Comment by facontidavide** [comment]
Unfortunately, it looks good to me

![image](https://user-images.githubusercontent.com/2822888/125188942-16966b00-e236-11eb-8221-e8ff5f182a69.png)

I do not support MacOS, sorry. Unless I get enough [Sponsors](https://github.com/sponsors/facontidavide) to buy a Mac, any issue related to MacOS will remain marked "wontfix".

Sorry :(

**Comment by jmailloux** [comment]
FYI, this seems to have magically fixed itself.  Maybe due to a reboot.
