### ISSUE TITLE
Feature Request: Two vertical cursors for time measurement

### ISSUE THREAD

**Issue by drdelayismysenpai** [facontidavide/PlotJuggler#481]
Having two signals of which one is a delayed version of the other, it would be great to measure the distance using two vertical cursors which show the time between them.

This would be a great first step towards frequency analysis, and possibly towards bode-plots and FFTs in the future.

**Comment by facontidavide** [comment]
I am not planning to implement this feature, unless someone wants to support its development. 

If you or someone else want to support the development of this, please contact me.
