### ISSUE TITLE
build on windows: need to manually copy .dlls?

### ISSUE THREAD

**Issue by patzf** [facontidavide/PlotJuggler#482]
# Problem description
I managed to build an executable of PlotJuggler on my windows machine but it seems I need to manually copy .dll files to the build dir and also copy the platform plugin .dlls to the build dir and place it under the subdir /platforms which quite tool me some time to figure out.
Can someone explain why those dependencies are not "copied over" during the build process? I am just getting started with cmake (and Qt).
 
# Steps to reproduce (important)

- Window10, 64bit
- cloned repository and checked out tag (release) 3.2.1
- set up Qt (Qt 5.15.2)
- set up MinSYS2 and installed MinGw64 (mingw81_64) 
- set up cmake-3.21.0-windows-x86_64
- set up paths in win32build.bat accordingly
- execute win32build.bat

starting the exe complains about missing .dlls so manually copied from Qt\5.15.2\mingw81_64\bin to build\
Qt5Core.dll
Qt5Gui.dll
Qt5Network.dll
Qt5Svg.dll
Qt5Widgets.dll

starting the exe complains about not initializing any platfom plugins, so manually copying all .dlls from
Qt\5.15.2\mingw81_64\plugins\platforms to build/platforms

**Comment by facontidavide** [comment]
This problem is common to any qt application and it is not a specific issue of plotjuggler.

Please Google "qt windows deployment"
