### ISSUE TITLE
Where did the quaternion conversion go?

### ISSUE THREAD

**Issue by julianoes** [facontidavide/PlotJuggler#484]
Thanks for PlotJuggler, you are great!

# Problem description

I'm trying to use the quaternion to Euler angle conversion but I can't find it.

# Steps to reproduce (important)

- I'm using PlotJuggler 3.2.0 on Linux.
- I don't see the quaternion conversion in the list.

![Screenshot from 2021-07-28 08-38-17](https://user-images.githubusercontent.com/1419688/127276133-a42524c3-6291-4249-a59d-d59070627a25.png)

What am I missing?

**Comment by facontidavide** [comment]
You are missing that quaternion conversion is not a default function library :) 
You should write it yourself and add it to your Function Library.

The good news is that I am working on a much better alternative in 3.3.
