### ISSUE TITLE
minimal step when replay rosbag

### ISSUE THREAD

**Issue by lanyusea** [facontidavide/PlotJuggler#486]
Thanks for contributing to PlotJuggler. You are great!

# Problem description

the minimal step is about 0.045s when replaying topic

# Steps to reproduce (important)

we set the timestamp as `header.stamp` and the step size into 0.01

![DC5A91DF-E5B8-A8EE-977E-CF17D66BD5A2](https://user-images.githubusercontent.com/2766729/127459829-4c4b1ad1-892b-4c15-b0f7-6e009de977bb.png)

but when replaying the topic, the minimal step (by pressing left/right arrow keys on the keyboard) is about 0.045s, which is larger than the time difference between two neighbour frames

![1EB08046-0BA0-1F11-05EA-024F78334092](https://user-images.githubusercontent.com/2766729/127460211-e27b9bca-a6c8-4314-9ca4-73cdda9e4e38.png)
![147BCEE1-E277-EFB3-BCA5-26E0E0208949](https://user-images.githubusercontent.com/2766729/127460221-00dbddf9-9c80-4739-80eb-00a9ab1bce76.png)
![61F316EC-0E7D-3766-9CC7-A5F689F0C5A2](https://user-images.githubusercontent.com/2766729/127460227-791f97d6-70ee-4488-aca0-4fa9c8ac3900.png)

how could we make it more accurate? 

- Describe your platform / Operative System.

The plotjuggler version is 3.1.2, running in Ubuntu 18.04

**Comment by facontidavide** [comment]
I can see that there is a tradeoff there that may not make everybody happy.

My only suggestion is... don't use the left/right keys, but move the vertical timetracker instead with **SHIFT+ Left Mouse**.
