### ISSUE TITLE
Is there a way to change line width in the GUI?

### ISSUE THREAD

**Issue by peasant98** [facontidavide/PlotJuggler#487]
Thanks for contributing to PlotJuggler. You are great!

# Problem description

I was wondering if we could change the line width of visualized topics in Plotjuggler -- currently, they are pretty thin and it's hard to see them when using graphs for things like presentations or papers.

# Steps to reproduce (important)

- Plot any topic in PlotJuggler to see.

**Comment by facontidavide** [comment]
I am not planning to add this kind of customization, for the time being, sorry.
