### ISSUE TITLE
MathEquations order should respect linkedSource dependencies on layout exporting

### ISSUE THREAD

**Issue by lukegluke** [facontidavide/PlotJuggler#488]
Custom math functions could use other functions as source, it must be take into account on layout exporting. 

To reproduce issue:
1. Load simple.csv datasample.
2. Create custom series `A2` (return value*2) based on `A` data, add it to plot.
3. Create another function `A4` (return value*2) based on `A2`, add it to plot.
4. Export layout
5. **Delete everything (ctrl+shift+x)**
6. Import layout
7. While `A4` curve is in legend it isn't plotted. One needs to go to `A4` edit dialog and reenable `A4` curve to see its data on plot.

It seems that on export `customMathEquations` section is filled without any rules, so `A4` function can be placed in first and when imported app doesn't know linkedSource `A2` yet, so curve is not plotted.
If manually correct functions order in layout xml file it is imported without issues.

Also application will crash If you skip step 5 and choose remove the previously loaded data.
But it is seems to be another issue, because it also happens with just one `A2`.

**Comment by facontidavide** [comment]
I think this is fixed
