### ISSUE TITLE
[Feature Request] Save custom Timestamp Format Strings

### ISSUE THREAD

**Issue by Bartimaeus-** [facontidavide/PlotJuggler#496]
When opening csv files that contain timestamps in a format that PlotJuggler can't automatically recognize it will prompt you to enter a QDateTime format string. It would be nice to enhance this feature by allowing you to save formats that are used often in your data files so you could select them from a listbox or similar in the dialog window.

![image](https://user-images.githubusercontent.com/2954254/130986773-944644e6-4ec7-4bf5-90e3-b149372334ad.png)

The usecase here is having to open csv files that are generated from different data acquisition equipment that each have slightly different formats.

(Using PlotJuggler 3.1.1 on Windows 10)

**Comment by facontidavide** [comment]
Brand new CSV plugin dialog :) 

![image](https://user-images.githubusercontent.com/2822888/132135298-20df5253-2929-4655-aa1c-525c0829b84f.png)
