### ISSUE TITLE
[Feature Request] Display Preview for Unrecognized Timestamp Formats

### ISSUE THREAD

**Issue by Bartimaeus-** [facontidavide/PlotJuggler#497]
Request to add a preview of the unrecognized timestamp in the dialog window that is created when opening csv files that contain timestamps in a format that PlotJuggler can't automatically recognize.

![image](https://user-images.githubusercontent.com/2954254/130989706-1d8eab26-0321-4f6e-bddb-51fe7a108a09.png)

Currently you have to go open the file in a separate editor to view the timestamp format to see what it should be

(Using PlotJuggler 3.1.1 in Windows)

**Comment by facontidavide** [comment]
To be implemented in 3.3.0
