### ISSUE TITLE
UDP Streaming Server Plugin Data Source Timestamp Not Applied

### ISSUE THREAD

**Issue by willz1200** [facontidavide/PlotJuggler#499]
Thanks for creating PlotJuggler. Its a great tool!

I'm currently streaming JSON into PlotJuggler over UDP. I have a "timestamp" field in the root of the JSON structure. After ticking the "use field [timestamp] if available" check box, I'd expect the data points to be aligned to the "timestamp". supplied in the structure. However it appears that they're only being aligned to the "__time" which is the internal receive time of the UDP JSON structure.
 
It looks like the original pull request for this feature (#152) mentions data source timestamps didn't work back then. Is this still the case or am I miss something?

I'm using PJ 3.1.1 on Windows

Thanks for the help :)

**Comment by jwdfki** [comment]
I have the same problem here is an image showing how it looks like.
![grafik](https://user-images.githubusercontent.com/35038728/133485465-ffda9273-d240-4e7c-a1df-2bbfa566daeb.png)

On the left are the messages sent to PJ. The plot should show a straight line y=x but it plots "timestamp" against the receive timestamp. Which also results in kinks in the line.
I tried to find the bug but as far as I could see everything seems to be in place that this should work. Maybe the option is just never propagated to the NlohmannParser::_use_message_stamp field?

This occured on both PJ 3.1.0 and 3.1.1 on Windows

**Comment by rraetz** [comment]
Having the exact same bug with PJ 3.1.1. I tried JSON and msgpack. Does anybody know if the same bug still exists in 3.2.0 when using with Linux?

**Comment by facontidavide** [comment]
You have the option "Remove time offset" enabled.

![image](https://user-images.githubusercontent.com/2822888/133933568-68d72251-b3aa-437a-abed-30b3e25bfd3c.png)

You should use the latest 3-3-0 and see if the problem persists or not.

If it does, I will reopen this issue.
