### ISSUE TITLE
Does it work as an RQT plugin?

### ISSUE THREAD

**Issue by davetcoleman** [facontidavide/PlotJuggler#5]
That would be a great feature.

This app looks really useful! I'd also love to see this as a default RQT plugin.

**Comment by facontidavide** [comment]
I honestly don't know how comlicated it would be. It was concived as a standalone app to provide a more integrated workflow.
I will investigate this option in the future, though.

**Comment by facontidavide** [comment]
PlotJuggler is already big and complex enough to make it too hard to squeeze into a RQT plugin.
I am temporary closing this issue.
