### ISSUE TITLE
can't edit curves on xy plot mode

### ISSUE THREAD

**Issue by zhangshengping** [facontidavide/PlotJuggler#500]
Thanks for contributing to PlotJuggler. You are great!

# Problem description

import data from csv file, and create a xy plot.
but i **can't edit curves**.
I build it from souce on main branch

# Steps to reproduce (important)

- import csv file
- create a xy plot 
- edit curves, but failed
[log440_akm_status_log_0.csv](https://github.com/facontidavide/PlotJuggler/files/7075958/log440_akm_status_log_0.csv)

**Comment by facontidavide** [comment]
If I understand you correctly, you are right and that can not be done. XY plot are not new curves but a visual representation, therefore you can't use them as "input" for custom curves

**Comment by zhangshengping** [comment]
I'm sorry for my poor english. 
I want to display XY plot as dot and line , but I can't do this!
but it seem work on version 3.2.
![cap](https://user-images.githubusercontent.com/6234787/131426996-96d998ba-151a-4c2a-8988-0f55031db68d.png)
