### ISSUE TITLE
Couldn't find executable named "PlotJuggler" (ROS Kinetic)

### ISSUE THREAD

**Issue by antoan** [facontidavide/PlotJuggler#504]
I have the same issue as #372

To reproduce:

rosrun plotjuggler plotjuggler

[rosrun] Couldn't find executable named plotjuggler below /opt/ros/kinetic/share/plotjuggler
[rosrun] Found the following, but they're either not files,
[rosrun] or not executable:
[rosrun]   /opt/ros/kinetic/share/plotjuggler

Operative System: Ubuntu Xenial 16.04

**Comment by facontidavide** [comment]
Sorry, Kinetic is gone

![david-tennant-not-my-problem](https://user-images.githubusercontent.com/2822888/151663007-555610a7-aa32-4650-a499-94fb398f4af9.gif)
