### ISSUE TITLE
Streaming buffer length timescale

### ISSUE THREAD

**Issue by wzli** [facontidavide/PlotJuggler#506]
I tried streaming messages that have integer timestamps in miliseconds instead of seconds to avoid floating point errors. The max buffer length is currently capped to 100 in version 3.2.0 which limits the window to only 0.1s capture. 

I think it would be useful to either:
- Allow a larger streaming buffer length
- Allow users to specify units for the timestamp field
- Limit the buffer window by fixed sample count instead of fixed time window

**Comment by facontidavide** [comment]
That is easy :) 

![Selection_514](https://user-images.githubusercontent.com/2822888/132121511-37fc7847-5ced-436a-888c-ddc8a47bf2ad.png)
