### ISSUE TITLE
Can't add timeseries to plots in Windows (PlotJuggler 3.3.0)

### ISSUE THREAD

**Issue by Bartimaeus-** [facontidavide/PlotJuggler#507]
Unable to add time series to plots in PlotJuggler 3.3.0 compiled for Windows:

https://user-images.githubusercontent.com/2954254/132111004-65d38844-bcef-4b8f-aaee-0632d49c1677.mp4

Same file works in Linux:

https://user-images.githubusercontent.com/2954254/132111010-e2fda361-b3b1-44d5-ad8d-410395704472.mp4

Test File attached:
[US06_drive_profile.csv](https://github.com/facontidavide/PlotJuggler/files/7110682/US06_drive_profile.csv)

**Comment by facontidavide** [comment]
I am working to fix this. The entire 3.3.0 version seems to be broken on Windows

**Comment by facontidavide** [comment]
fixed. thanks for reporting

![image](https://user-images.githubusercontent.com/2822888/132125005-c5433101-d1a3-45ee-8632-8e155b2d673a.png)
