### ISSUE TITLE
Layout Files Can Cause Loading of Unused Data Files (may lead to crash)

### ISSUE THREAD

**Issue by Bartimaeus-** [facontidavide/PlotJuggler#516]
(PlotJuggler 3.3.0 on Windows 10)

Not a showstopping bug but reporting anyways:

Layout files that have the "Save data source" option selected may include files that were previously unloaded when the Layout file was created, and user input on a dialog window can cause PlotJuggler to crash when loading the layout file

How this was discovered:
-Have a Plotjuggler window open from a previous session with data loaded
-Load new data file and have PlotJuggler remove the previous data
-Set up layout for new data and save the Layout file with the "Save data source" option selected ("save custom transformations" also selected in my case but suspect this isn't relevant)
The clip below shows an example of creating the layout file (also see the note below)

https://user-images.githubusercontent.com/2954254/132954363-b817c67b-1d5f-464d-8a8a-3902f9f966d7.mp4

Note: I tried doing this several different ways and in one attempt (I think if the first file is loaded but you don't do anything with the data before loading the second) the layout file will not include the first file. The example video here may be such a case. I know it is repeatable if you load the first file, create a custom timeseries and plot it and then load the second file and unload the old data.

When the layout file is later loaded, the original file that was open is loaded, and then the second file is loaded and the user is given the following prompt:
![image](https://user-images.githubusercontent.com/2954254/132954451-4191b7bf-bff5-40a4-aab1-814ac2cc197c.png)

PlotJuggler will crash if the user selects "No" in this dialog window:

https://user-images.githubusercontent.com/2954254/132955865-e9fba97a-8874-4e78-809e-19b8b6378331.mp4

Selecting "Yes" to remove the previously loaded data will let the second data file load without issue

https://user-images.githubusercontent.com/2954254/132955872-4cd3c14a-f060-4b09-980c-3b27014ba4f4.mp4

Interestingly the layout file contains multiple files that had been previously loaded during the session, but only the last one to have been unloaded seems to get loaded when opening the layout file in PlotJuggler
![image](https://user-images.githubusercontent.com/2954254/132956002-e99eb180-388e-4615-ae48-9922d8d297f0.png)

It seems like the inclusion of files that have been unloaded doesn't serve a functional purpose and is undesirable behavior (this could lead to leaking sensitive information by including file info that was not intended to be shared)

Example files attached:
[LayoutMultiFileLoadExample.zip](https://github.com/facontidavide/PlotJuggler/files/7148220/LayoutMultiFileLoadExample.zip)

**Comment by facontidavide** [comment]
I just pushed a change that will clean correctly the list of previously loaded files.

Let me know if you have further problems
