### ISSUE TITLE
Opening a CSV File With Duplicate Header Entries Makes PlotJuggler Crash

### ISSUE THREAD

**Issue by Bartimaeus-** [facontidavide/PlotJuggler#524]
Attempting to open a csv file that contains two or more header entries with the same contents causes PlotJuggler to crash without warning

Example header:
`timestamp,A,A,C,D`

Attached is the command line output when PlotJuggler crashes:

[PlotJuggler_CSV_MultipleHeader_Crash_Print_Outputs.txt](https://github.com/facontidavide/PlotJuggler/files/7230341/PlotJuggler_CSV_MultipleHeader_Crash_Print_Outputs.txt)

Having PlotJuggler check the header for duplicate entries and either aborting the file load with an informational message or appending a sequential number to the end of the duplicate entries to make them unique would be great.

Having non-unique header entries in a csv is definitely not good practice, in this case the csv file that caused this issue was generated from a data analysis software that was exporting separate time columns for each data series:

`Time,Data1,Time,Data2,Time,Data3`

Multiple time axis from the same csv is definitely not a format that PlotJuggler currently supports, the intent was to ignore the time columns and use the row number as the time axis.

**Comment by facontidavide** [comment]
Nice catch. I will fix it soon.

The correct behavior is, in my opinion, to simply forbid column with identical names (and stop loading such files).

In the  example you provided` Time,Data1,Time,Data2,Time,Data3`, an option could be to append some automatic suffix to identical columns, but i don't think plotjuggler should handle this.

**Comment by facontidavide** [comment]
![image](https://user-images.githubusercontent.com/2822888/135584604-e99d05f5-e6ca-4b17-bf1c-c6a5051fdf5c.png)
