### ISSUE TITLE
Slashes in CSV Header Entries Cause Nested Tree Entries in Timeseries List

### ISSUE THREAD

**Issue by Bartimaeus-** [facontidavide/PlotJuggler#525]
Slashes in csv file headers cause PlotJuggler to create nested tree entries in the Timeseries List in the left panel

Example header:
`timestamp,A,B,KM/H,D`

![image](https://user-images.githubusercontent.com/2954254/134786062-d55354a8-1e7b-414b-ac2b-b45ab9c72b9a.png)

Funny enough this doesn't have a visible impact on the display of the name in the plot legend because all of the slashes are already displayed:
![image](https://user-images.githubusercontent.com/2954254/134786151-5014cc67-f54b-45c0-896d-57f26949a7bf.png)

**Comment by Bartimaeus-** [comment]
I just discovered that if you use the csv exporter the header will have the following format:

`__time,simple_parse_timestamp/A,simple_parse_timestamp/B,simple_parse_timestamp/D,simple_parse_timestamp/KM/H`

which is displayed in the tree as:
![image](https://user-images.githubusercontent.com/2954254/134786239-cb9a344b-670a-44f9-b6cf-8dce779ca426.png)

Which seems like an interesting way for maintaining the original tree format when opening a csv file that was created from PlotJuggler-- is this an intended feature that I've mistaken for a bug? Perhaps PlotJuggler could use the backslash ( \ ) or pipe ( | ) for this purpose instead of the forward slash ( / ) which is more likely to be used to indicate the unit of data in a header context?

**Comment by facontidavide** [comment]
slashes are by definition THE way tree view is defined.

I understand that in there could be corener cases like this one, but all the existing plugins (including third party) use this.

You can use this potion, to avoid the tree view: 

![image](https://user-images.githubusercontent.com/2822888/134787653-193464d2-ab9e-42d9-a9d7-93e397658e74.png)
