### ISSUE TITLE
[Feature Request] Add Reference Info for Timestamp String Format

### ISSUE THREAD

**Issue by Bartimaeus-** [facontidavide/PlotJuggler#527]
Some kind of reference or hint to the user where to look for the formatting strings for Timestamp parsing would be a big quality of life improvement for importing CSV files.

The formatting conventions aren't anything crazy but I'm not fluent in it and have to try multiple times with some files before I get it right.

The old style of import dialog window had a note referring to QDateTime::fromString. This text was helpful because it made it faster to search for the documentation:
![image](https://user-images.githubusercontent.com/2954254/134788553-3eb19ab1-9346-473a-8485-14bff5fb9bd9.png)

A hyperlink to the docs could work if you don't want to put the full tables (though I can see reasons for not wanting to include links that could go dead)
https://doc.qt.io/qt-5/qtime.html#toString
https://doc.qt.io/qt-5/qdatetime.html

Embedding the tables somewhere into the GUI so you can see it on the side while you're entering the format would be the most useful but really even just a faster way to get to the info online would be a big help
![image](https://user-images.githubusercontent.com/2954254/134788656-e2ad381a-34c9-4497-97e4-29f32f6c87f7.png)

Thanks for all of the improvements that you've made so far, this is a great tool that I have been getting a lot of mileage out of!

**Comment by facontidavide** [comment]
Quick fix :) 

![image](https://user-images.githubusercontent.com/2822888/135585924-b20d95d0-0193-4bd2-8d2e-6d1222d52d43.png)
