### ISSUE TITLE
Duplicate column names in CSV file cause crash without error message

### ISSUE THREAD

**Issue by rustyoz** [facontidavide/PlotJuggler#529]
# Problem description

If a csv file is imported has duplicate column names in the heading Plotjuggler will crash without explanation. 
[motordata.csv](https://github.com/facontidavide/PlotJuggler/files/7233553/motordata.csv)

# Steps to reproduce 
import csv file with duplicate names in the column headers. (demo attached

# Describe your platform / Operative System.
Windows 10 
Plotjuggler 3.3.0

**Comment by potaito** [comment]
Duplicate of https://github.com/facontidavide/PlotJuggler/issues/524

**Comment by facontidavide** [comment]
![image](https://user-images.githubusercontent.com/2822888/135584455-36ddbd3a-7b1d-46be-b3be-5cd6cd11e86f.png)

Fixed
