### ISSUE TITLE
Plots get blurred

### ISSUE THREAD

**Issue by kminoda** [facontidavide/PlotJuggler#530]
The plots on plotjuggler always get blurred on my PC. Please look at an uploaded video as it's difficult to explain in words.
I am using ROS2 Galactic on Ubuntu 20.04 LTS, running the app using `ros2 run plotjuggler plotjuggler`.

I am sorry that I cannot reproduce this problem on the other PCs... nobody around me (using plotjuggler on ROS/ROS2) have ever encountered this issue either.

Thanks in advance!

https://user-images.githubusercontent.com/44218668/134861902-0ac9d199-20b9-4630-a66a-601924bda6ed.mp4

--
Here are some screenshots for a reference. The first figure shows the blurred plot. For comparison, I also uploaded a plot with the less blur-ish effect.
![abnormal](https://user-images.githubusercontent.com/44218668/134861971-2f54d395-00d9-43c3-8014-eef6c36f32aa.png)
![normal](https://user-images.githubusercontent.com/44218668/134861983-e6825b4b-dfce-41e4-8c1c-fed8bff1cca1.png)

**Comment by facontidavide** [comment]
disable OpenGl in Settings

**Comment by kminoda** [comment]
It worked! Thanks for the quick response.
