### ISSUE TITLE
one char"..."  cannot be compiled and M_PI M_PI_2 std::array cannot find on Windows visual studio

### ISSUE THREAD

**Issue by dzywater** [facontidavide/PlotJuggler#540]
~\3rdparty\Qt-Advanced-Docking\src\ElidingLabel.cpp
one char"..." cannot compiled
line: 69
line: 174
It is workable with  three dots"..."

~\plotjuggler_plugins\ToolboxQuaternion\quaternion_to_rpy.cpp
~\plotjuggler_plugins\ToolboxQuaternion\toolbox_quaternion.cpp
https://github.com/PlotJuggler/plotjuggler-ros-plugins/plugins/ros2_parsers\quaternion_msg.h
(1)cannot find std::array
(2)cannot find M_PI and M_PI_2
It is workable after adding following code at beginning of files
#include<array>
#ifndef M_PI
#define M_PI 3.1415926535897932384626433832795
#define M_PI_2 (M_PI * M_PI)
#endif

**Comment by kutukvpavel** [comment]
For MSVC you have to modify the sources a bit if you use the quaternion plugin. As for 3 dots, I had no issues with that file and VS2019.

For math constants to be defined you #define _USE_MATH_DEFINES before #include <math.h> (https://stackoverflow.com/questions/6563810/m-pi-works-with-math-h-but-not-with-cmath-in-visual-studio).

Also I had to add

#include <tuple>
#include <array>

to get rid of array-related errors.
It seems those library issues only affect quaternion plugin, so, all in all, you add this to quaternion_to_rpy.h:
`#include <tuple>
#include <array>
#define _USE_MATH_DEFINES
#include <math.h>`

**Comment by facontidavide** [comment]
thanks @kutukvpavel  to answer this question. Closing
