### ISSUE TITLE
some bugs appeared recently (?)

### ISSUE THREAD

**Issue by mkolodziejczyk-piap** [facontidavide/PlotJuggler#547]
Hi,
Ubuntu 20, ROS Foxy, plotjuggler 3.3.0 and 3.3.1

Recently some annoying bugs started to occur. For example
* For scatterplot I can't "Edit curves.." - the window has all the buttons disabled. Also sometimes the following window appears first
![Screenshot from 2021-10-28 12-40-43](https://user-images.githubusercontent.com/73108914/139263385-62b9b01f-5519-4ed9-b4b1-8772ff6df817.png)
* there are various errors in shell like:
```
QPixmap::scaled: Pixmap is a null pixmap
QCursor: Cannot create bitmap cursor; invalid bitmap(s)

QBasicTimer::start: QBasicTimer can only be used with threads started with QThread
```
* after opening rosbag2 main level of topics is "metadata"
![Screenshot from 2021-10-28 15-12-09](https://user-images.githubusercontent.com/73108914/139264087-9a592640-0572-46aa-8083-77c0ed55107b.png)

First I thought it's due to recently I switched to recording bags with [rosbag2 foxy-future](https://github.com/ros2/rosbag2/tree/foxy-future) branch. But I double checked older recordings on  rosbag2 foxy binaries. Also checked on my colleague's workstation and the same happens. Also checked Galactic rosbag2/plotjuggler - the same. I wonder if maybe some recent QT update could be the reason?

Regards,

**Comment by facontidavide** [comment]
closing, until a way to reproduce it is provided
