### ISSUE TITLE
Issue with high res screen

### ISSUE THREAD

**Issue by tkazik** [facontidavide/PlotJuggler#548]
# Problem description

The left pane of plotjuggler looks cramped when used on a high res screen.
![plotjuggler_4k](https://user-images.githubusercontent.com/15689124/139342877-343d211d-1534-41e1-85c4-be11d1411649.jpg)

# Steps to reproduce

- Ubuntu 20.04
- plotjuggler v3.3.1
- fractional scaling at 150%

The `fractional scaling` seems to be the culprit, as it looks nice if set to 100%...but my eyes prefer 150% ;)
Thx for your great work!

**Comment by RicardoM17** [comment]
Same here. Did you manage to find a fix?

**Comment by facontidavide** [comment]
not a priority of mine. If anybody wants to contribute with a PR...

**Comment by RicardoM17** [comment]
> not a priority of mine. If anybody wants to contribute with a PR...

It probably just needs something like:

> --force-device-scale-factor=1.5 

Somewhere. I had a similar issue that was fixed like that with Spotify. In this case it was in the .desktop file.

I can try to have a look if I have time but if you can point me where to look that would help.

**Comment by facontidavide** [comment]
it should be fixed
