### ISSUE TITLE
[ROS-noetic] I can't find the format for rosbag to import data!

### ISSUE THREAD

**Issue by Lenny-Lee-ustb** [facontidavide/PlotJuggler#553]
# Problem description

I can't find the format for rosbag to import data

# Steps to reproduce (important)

ubuntu20.04&noetic
I can only find *.csv and *.ulg format in Files->Data->import.

**Comment by facontidavide** [comment]
Dear User,

you probably:
- ignored the Message "Missing package [plotjuggler-ros]" in the popup at the beginning,
-  you haven't read the readme and 
- you haven't looked at previous solved issues.

Please do: 

`sudo apt install ros-noetic-plotjuggler-ros`

**Comment by Lenny-Lee-ustb** [comment]
> Dear User,
> 
> you probably:
> 
> * ignored the Message "Missing package [plotjuggler-ros]" in the popup at the beginning,
> * you haven't read the readme and
> * you haven't looked at previous solved issues.
> 
> Please do:
> 
> `sudo apt install ros-noetic-plotjuggler-ros`

I solved this after your guidence. 
The software is pretty good and efficient. 
Thanks a lot!!
