### ISSUE TITLE
Persistent lines with ZMQ streaming

### ISSUE THREAD

**Issue by milesfrain** [facontidavide/PlotJuggler#558]
# Problem description

I'm observing ghosting behavior when plotting streaming data on my system. ~Old lines are only cleared correctly in 5-second intervals.~ **Edit: Old lines are only cleared when labeled tick marks are added or removed from the x-axis.** I can also force continuous correct clearing by dragging an edge of the window to continuously resize it.

Running the `3.2.0` [binary](https://github.com/facontidavide/PlotJuggler#binary-installers-with-basic-plugins).

I think this is more of an issue with my system (Ubuntu 20.04). Things are working fine on another linux machine, so I doubt sharing a data sample will help other folks reproduce this issue either. I suspect this rendering issue might be related to using a wimpy integrated GPU (Intel HD Graphics 620). I'll try some more testing with additional machines to track down a common theme. Let me know if there's some additional debugging I can enable to help get to the bottom of what's going wrong.

https://user-images.githubusercontent.com/3578681/140586914-e177c72f-a66b-476b-a719-7906b6e7248c.mov

**Comment by facontidavide** [comment]
disable OpenGL in Preferences
