### ISSUE TITLE
Segmentation fault on exit (M1 chipset)

### ISSUE THREAD

**Issue by erickisos** [facontidavide/PlotJuggler#560]
# Problem description

I built PlotJuggler today for first time, and I discovered that every time I close the window (through close button) it always launch a `segmentation fault` like in the screenshot.

![Captura de Pantalla 2021-11-07 a la(s) 20 35 32](https://user-images.githubusercontent.com/14081477/140675519-063d8fdf-daaa-463f-92a7-ce2225519652.png)

# Steps to reproduce (important)

It's important to consider a few things because it could be an error of the platform and not necessarily the application.

- macOS Big Sur 11.6 on Apple M1
- I don't have any ros instance installed (mainly because the lack of support for the platform(?))

I can share the full output if needed, I just want to be sure if this is a problem for the platform or if it's happening with the new version of PJ.

**Comment by facontidavide** [comment]
This is fixed in Protobuf, but VideoViewer is still crashing :(

**Comment by facontidavide** [comment]
fixed
