### ISSUE TITLE
Parse common boolean strings for diagnostics

### ISSUE THREAD

**Issue by Timple** [facontidavide/PlotJuggler#566]
The diagnostic parser is awesome!

# Problem description

Since diagnostics have to be strings, and are typically meant for human eyes, we find ourselves putting strings like on/off or true/false in there.
However these go unnoticed by plotjuggler.

# Steps to reproduce (important)

- Interpret a diagnostic key/value message like this: pump_state: 'on'.

# Feature request
Parse common boolean values such as on/off, true/false, yes/no.

**Comment by facontidavide** [comment]
yes, this is on my todo list

**Comment by facontidavide** [comment]
fixed in 3.4.1
