### ISSUE TITLE
In newest version, layout clears itself everytime we open a rosbag

### ISSUE THREAD

**Issue by roangel** [facontidavide/PlotJuggler#567]
So, I am using plotjuggler for around a year and it has been awesome, it makes us save TONS of time when trying to debug a problem. Thanks a lot for this tool.

So, regarding my problem, usually I have different rosbag files that contain the exact same topic names, but different data inside. Before, in version 3.2.0, when I had a layout with some data plotted, then switched to a new rosbag file with same topic names but different data, it just smoothly kept the layout and just changed the data. This was extremely convenient for debugging. However, in the latest version, when I change the file, the layout completely goes blank and then I have to, every single time, bring up the signals I wanted to analyze.

It would be really nice if this could go back to how it was before.

Thanks a lot!

**Comment by roangel** [comment]
Yes, it's 3.3.3. Just checked and it definitely happens.

**Comment by facontidavide** [comment]
Can you please send me a sample data/layout. It will make my life much easier :)

**Comment by roangel** [comment]
Here is a sample bag that you can test with:
[test_plotjuggler.zip](https://github.com/facontidavide/PlotJuggler/files/7569709/test_plotjuggler.zip)

**Comment by roangel** [comment]
Sample layout:
[test_plotjuggler_layout.zip](https://github.com/facontidavide/PlotJuggler/files/7570124/test_plotjuggler_layout.zip)

**Comment by facontidavide** [comment]
I think it is fixed on master. Can you check?
