### ISSUE TITLE
how to use lua write custom function with single input multioutput

### ISSUE THREAD

**Issue by dysenustc** [facontidavide/PlotJuggler#577]
Thanks for contributing to PlotJuggler. You are great!

# Problem description
my data  is save as bit, and i want show all bit result, how can i use lua to write custom single input and multi output function
single output sames too redundant

Describe the problem and the expected behavior. Use screenshots of video if approriate.

# Steps to reproduce (important)

- Describe your platform / Operative System.
- Check if the problem can be reproduced using the dummy data created by the command line argument "-t" or one of the files in the folder "datasamples".
- If it can't be reproduced with the dummy data, __please__ share the CSV file or the rosbag that can be used to reproduce the problem.

**Comment by facontidavide** [comment]
With the new Reactive Lua scrips described here, now you can.
not super straightforward but possible!

https://slides.com/davidefaconti/plotjuggler-reactive-scripts/fullscreen
