### ISSUE TITLE
I can only perform Quaternion to RPY once

### ISSUE THREAD

**Issue by sverrevr** [facontidavide/PlotJuggler#587]
# Problem description
If I have performed tools/"Quaternion to RPY" once then I cannot do it again (on other data). The save button the second time is grayed out and cant be pressed. 

![bilde](https://user-images.githubusercontent.com/9085288/151536246-cfcf13a3-8dac-4031-bcf9-0b5532661a68.png)

# Steps to reproduce (important)

- On windows 10
- Load some data
- Perform tools/"Quaternion to RPY" once
- Perform tools/"Quaternion to RPY" again

**Comment by sverrevr** [comment]
Recreated on master on wsl2 running Ubuntu 18.04

**Comment by facontidavide** [comment]
I guess you want to overwrite the old values, right?

**Comment by sverrevr** [comment]
I wanted to define further values, but overwriting would also be useful. 
So even though I give it a new name I am unable to press save

**Comment by facontidavide** [comment]
Just pushed a fix (and more). Check latest commit on **main**

**Comment by sverrevr** [comment]
Works like a charm! I'm impressed with how fast you solved this issue! thanks :)
