### ISSUE TITLE
Is there a way to plot JointTrajectoryPoint Message from ROS?

### ISSUE THREAD

**Issue by Joo236** [facontidavide/PlotJuggler#590]
I would like to visualize the joint trajectory points (http://docs.ros.org/en/api/trajectory_msgs/html/msg/JointTrajectoryPoint.html) using ROS melodic. Is there any feature for this available ?

**Comment by salmagro** [comment]
@facontidavide has just released version 3.4; it might be worth trying it. (Reactive scripts)
https://github.com/facontidavide/PlotJuggler/releases/tag/3.4.0

Take a look also at the branch under development:
https://github.com/PlotJuggler/plotjuggler-ros-plugins/tree/trajectory

A similar topic was also mentioned on:
https://github.com/facontidavide/PlotJuggler/issues/305#issuecomment-1024905349
