### ISSUE TITLE
Plotjuggler does not show alias of curves

### ISSUE THREAD

**Issue by brkay54** [facontidavide/PlotJuggler#602]
# Problem description

Plotjuggler shows the curve's topic addresses but not show the alias. I am using ubuntu 20.04.3 LTS and ROS2 Foxy.

![Screenshot from 2022-02-11 12-40-48](https://user-images.githubusercontent.com/45468306/153569402-358e84f3-519a-44c6-8f56-b4b7adfde27d.png)

Layout xml file:

> 
>       <DockArea name="Lateral Controller Info">
>        <plot mode="TimeSeries" style="Lines">
>         <range bottom="-1.152264" top="1.022526" right="118.796638" left="76.172500"/>
>         <limitY/>
>         <curve name="/control/output/lateral/diagnostic/diag_array/data.5" color="#1f77b4">
>          <transform alias="lateral error(m)" name="Scale/Offset">
>           <options value_scale="1.0" time_offset="0" value_offset="0"/>
>          </transform>
>         </curve>
>         <curve name="/control/output/lateral/diagnostic/diag_array/data.8" color="#d62728">
>          <transform alias="yaw error(rad)" name="Scale/Offset">
>           <options value_scale="1.0" time_offset="0" value_offset="0"/>
>          </transform>
>         </curve>
>         <curve name="/control/output/lateral/diagnostic/diag_array/data.0" color="#1ac938">
>          <transform alias="steer cmd (final)(rad)" name="Scale/Offset">
>           <options value_scale="1.0" time_offset="0" value_offset="0"/>
>          </transform>
>         </curve>
>         <curve name="/control/output/lateral/diagnostic/diag_array/data.2" color="#ff7f0e">
>          <transform alias="steer cmd (FF-filtered)(rad)" name="Scale/Offset">
>           <options value_scale="1.0" time_offset="0" value_offset="0"/>
>          </transform>
>         </curve>
>         <curve name="/control/output/lateral/diagnostic/diag_array/data.3" color="#f14cc1">
>          <transform alias="steer cmd (FF-raw)(rad)" name="Scale/Offset">
>           <options value_scale="1.0" time_offset="0" value_offset="0"/>
>          </transform>
>         </curve>
>         <curve name="/control/output/lateral/diagnostic/diag_array/data.4" color="#9467bd">
>          <transform alias="steer measured(rad)" name="Scale/Offset">
>           <options value_scale="1.0" time_offset="0" value_offset="0"/>
>          </transform>
>         </curve>
>         <curve name="/control/output/lateral/diagnostic/diag_array/data.1" color="#17becf">
>          <transform alias="steer cmd (mpc-raw)(rad)" name="Scale/Offset">
>           <options value_scale="1.0" time_offset="0" value_offset="0"/>
>          </transform>
>         </curve>
>        </plot>
>       </DockArea>

**Comment by facontidavide** [comment]
it should be fixed
