### ISSUE TITLE
Loading valid .csv results in "Selected time in notstrictly  monotonic" error

### ISSUE THREAD

**Issue by mactro** [facontidavide/PlotJuggler#61]
The first time I load a csv file to PlotJuggler there is a pop-up asking to select the time axis. The file is loaded correctly. When I want to load another file with same data structure, there is "Selected time in notstrictly  monotonic" error. 

The only way I can get data to be loaded correctly then, is to change the name of time axis in the csv.

Example files (extensions changed to txt due to Github restrictions):
[test.txt](https://github.com/facontidavide/PlotJuggler/files/1487087/test.txt)
[test2.txt](https://github.com/facontidavide/PlotJuggler/files/1487088/test2.txt)

**Comment by facontidavide** [comment]
I think I fixed it... https://github.com/facontidavide/PlotJuggler/commit/48c5d0537257543650a03c1c16fe3d6703cd1a3b

**Comment by facontidavide** [comment]
By the way, thank you very much for reporting

**Comment by facontidavide** [comment]
Not quite there... I introduced an error :P

**Comment by facontidavide** [comment]
ok. know it works
