### ISSUE TITLE
Rosbag support in PlotJuggler 3 AppImage

### ISSUE THREAD

**Issue by TheExDeus** [facontidavide/PlotJuggler#611]
# Problem description

In versions <3 the AppImage is built with Rosbag support. It supports ROS everything (subscribe, publish), but I personally only use it for rosbags. To compile the plugins separately I need ROS, but I don't actually use it - only rosbags. I guess I can try installing ROS in docker, then build the plotjuggler ros plugins and copy them out of docker so my PlotJuggler 3 AppImage can find the plugins. Would that work or would it still need ROS?

I think it would be great if you packaged AppImage 3 just like you did with 2, so at least rosbags would be openable. Would that require some extra dependencies you didn't want or something else?

Thank you! This is an awesome (and basically the only) tool for looking into rosbags.

**Comment by facontidavide** [comment]
I decided that the AppImage will be compiled without ROS, too many headaches!

ROS user should use **apt install**
