### ISSUE TITLE
Possible issue with ROS 1 "sensor_msgs/JointState" - array fields not displayed

### ISSUE THREAD

**Issue by marco-tranzatto** [facontidavide/PlotJuggler#613]
First of all, let me thank you for creating and making this awesome software available!

# Problem description

ROS1 message of type "sensor_msgs/JointState" can be echoed on terminal but its array fields do not show up when trying to plot them (after rosbag has been loaded into plotjuggler). I also tried the solution from issue #374 but it did not help. See below screenshot.

![Screenshot_2022-03-01_16-21-48](https://user-images.githubusercontent.com/5328930/156196630-b3164610-98a4-4cc8-a7a5-de4e401765f4.png)

# Steps to reproduce (important)

- **Describe your platform / Operative System:** Ubuntu 20.04, ROS noetic, plotjuggler 3.4.1 (as shipped with `apt install ros-noetic-plotjuggler`)
- **Check if the problem can be reproduced using the dummy data created by the command line argument "-t" or one of the files in the folder "datasamples"**: sample data containing array can be correctly visualized.
- **If it can't be reproduced with the dummy data, __please__ share the CSV file or the rosbag that can be used to reproduce the problem.**: rosbag with example topic - [link](https://drive.google.com/file/d/11lo854ItYTXzG0KP4cBs-YZtsV0dvC6b/view?usp=sharing)

Thanks for any hint you might have on the issue.
Marco

**Comment by facontidavide** [comment]
This is happening because your ** name** array is empty.
This case is not taken into account

**Comment by marco-tranzatto** [comment]
thanks for your swift reply and explanation @facontidavide ! I'll update my code to make sure this does not happen.
