### ISSUE TITLE
I download the 3.4.0 in  windows and install it. But when I open it , the software flashback

### ISSUE THREAD

**Issue by khadegar** [facontidavide/PlotJuggler#617]
Thanks for contributing to PlotJuggler. You are great!

# Problem description

Describe the problem and the expected behavior. Use screenshots of video if approriate.

# Steps to reproduce (important)

- Describe your platform / Operative System.
- Check if the problem can be reproduced using the dummy data created by the command line argument "-t" or one of the files in the folder "datasamples".
- If it can't be reproduced with the dummy data, __please__ share the CSV file or the rosbag that can be used to reproduce the problem.

**Comment by facontidavide** [comment]
That text is my template. Aren't you taking the time to describe what "flashback" means? Seriously?

**Comment by khadegar** [comment]
I am very sorry.  I mean when I open it, it close after about 2 seconds.  I download the file  at your link
I am very thank you for your help

**Comment by facontidavide** [comment]
I will submit soon 3.4.3. Let me know if problem persists

**Comment by facontidavide** [comment]
close for inactivity
