### ISSUE TITLE
No ZMQ plugin

### ISSUE THREAD

**Issue by MrShedman** [facontidavide/PlotJuggler#619]
The ZMQ plugin has gone missing from latest version.

On either ROS1 or ROS2 I have no ZMQ plugin. I can also see in the latest appimage there is also no libDataStreamZMQ.so. Why is this missing?

My system:
- Ubuntu 20.04
- ROS1/2 (Noetic/Foxy)

**Comment by facontidavide** [comment]
if you don't have ZMQ installed in your system, the related plugin will not be built

**Comment by facontidavide** [comment]
I think a recent change should fix this
