### ISSUE TITLE
Plotjuggler package for galactic is missing

### ISSUE THREAD

**Issue by Gdanan** [facontidavide/PlotJuggler#623]
Hey,
I'm trying to install the Plotjuggler package and gets the following error each time:
`$sudo apt install ros-galactic-plotjuggler-ros
[sudo] password for gil: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ros-galactic-plotjuggler-ros
`

**Comment by facontidavide** [comment]
fixed
