### ISSUE TITLE
support for lcm data stream

### ISSUE THREAD

**Issue by binfengxueqian** [facontidavide/PlotJuggler#628]
Thanks for contributing to PlotJuggler. You are great!

# Problem description

I am using the LCM library for data communication and hope the plothuggler to suppor LCM data stream and parse of LCM message formats

the github of LCM is https://github.com/lcm-proj/lcm

**Comment by facontidavide** [comment]
Doable, I guess, but only as a paid development.
If anybody wants to sponsor this effort, let me know.

**Comment by binfengxueqian** [comment]
> Doable, I guess, but only as a paid development. If anybody wants to sponsor this effort, let me know.

How much will it cost？

**Comment by facontidavide** [comment]
Please reach me on davide.faconti@gmail.com 😊

**Comment by hxrkpib** [comment]
> Please reach me on [davide.faconti@gmail.com](mailto:davide.faconti@gmail.com) 😊

I also want this function and have sent you an email.

**Comment by facontidavide** [comment]
I took a quick look at LCM and I don't find something mandatory in this case, to implement it with PlotJuggler, a reflection API for the serialized messages.

In other words, using this as a reference: http://lcm-proj.github.io/lcm/content/tutorial-cpp.html
I need to be able to subscribe WITHOUT including the type

`exlcm::example_t`

If you find an example that shows how to do that. Let me know.

**Comment by lgkimjy** [comment]
Are there any updates on LCM support??
