### ISSUE TITLE
The time tracker is not appearing.

### ISSUE THREAD

**Issue by MoreTore** [facontidavide/PlotJuggler#630]
I am streaming with openpilot Cereal subscriber.
The time tracker is not appearing. I am using this fork https://github.com/MoreTore/PlotJuggler compiled on ubuntu 22.04 using the dockerfile included in the fork. I have my binaries as a release if that helps.

Describe the problem and the expected behavior. Use screenshots of video if approriate.

# Steps to reproduce (important)
git clone https://github.com/MoreTore/PlotJuggler
cd PlotJuggler
git submodule update --init
./build.sh

I run this with openpilot/tools/replay

![Screenshot from 2022-04-24 23-21-37](https://user-images.githubusercontent.com/104254025/165020479-77097547-bf4a-4526-b052-95ef9d1fd6d7.png)

**Comment by MoreTore** [comment]
If its an easy fix great, if not then its no big deal

**Comment by facontidavide** [comment]
that is **intentional**. It is disabled when streaming is active and will be activated when streaming is stopped or paused.
