### ISSUE TITLE
Cannot launch on WSL on Windows 11 (Ubuntu 18.04)

### ISSUE THREAD

**Issue by Pokornz** [facontidavide/PlotJuggler#634]
# Problem description

Something has changed between versions of PlotJuggler that influences the behavior when launching from AppImage on WSL on Windows 11.

For versions 3.1.1, 3.1.2, 3.2.0, I get a black window:
![image](https://user-images.githubusercontent.com/33861443/166469615-41454280-b148-47c6-acc5-514fd2537d41.png)

For versions 3.4.0, 3.4.1, it does not launch at all:
```
/tmp/.mount_PlotJuOKLuAM/AppRun.wrapped: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_PlotJuOKLuAM/AppRun.wrapped)
/tmp/.mount_PlotJuOKLuAM/AppRun.wrapped: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_PlotJuOKLuAM/usr/bin/../lib/libQt5Widgets.so.5)
/tmp/.mount_PlotJuOKLuAM/AppRun.wrapped: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_PlotJuOKLuAM/usr/bin/../lib/libQt5Gui.so.5)
/tmp/.mount_PlotJuOKLuAM/AppRun.wrapped: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_PlotJuOKLuAM/usr/bin/../lib/libQt5Core.so.5)
/tmp/.mount_PlotJuOKLuAM/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_PlotJuOKLuAM/usr/bin/../lib/libQt5Core.so.5)
/tmp/.mount_PlotJuOKLuAM/AppRun.wrapped: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_PlotJuOKLuAM/usr/bin/../lib/libpng16.so.16)
/tmp/.mount_PlotJuOKLuAM/AppRun.wrapped: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_PlotJuOKLuAM/usr/bin/../lib/libicui18n.so.66)
/tmp/.mount_PlotJuOKLuAM/AppRun.wrapped: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_PlotJuOKLuAM/usr/bin/../lib/libicuuc.so.66)
```
Version 2.8.4 launches, but is at this point severely outdated.

**NOTE**
I have originally installed PJ from apt install for ROS, but rosrun gave me the aforementioned black window. 
Later I tried compiling PJ and msgs from the source and roslaunch it, but same result.

# Steps to reproduce (important)

- Setup WSL on Windows 11, install Ubuntu 18.04
- Download the .AppImage, make it executable.
- Run the .AppImage

**Comment by facontidavide** [comment]
I am not supporting Ubuntu 18.04 anymore and even less WSL on Windows.

I am afraid I can't help.

**Comment by ulterzlw** [comment]
I face a similar problem in a docker container. You can try to disable OpenGL in the preference menu. microsoft/wslg#118
