### ISSUE TITLE
How to plot 3D graphs (XYZ) using plotjuggler?

### ISSUE THREAD

**Issue by adbidwai** [facontidavide/PlotJuggler#637]
@facontidavide and team, Thank you so much for this amazing plotting tool!

I want to plot 3D plots in the XYZ real space (for e.g coordinates of a mobile TF frame) using `plotjuggler`. Does it support 3D plots? If yes, how do I use it?

I tried to check the documentation available but I could not find a way to plot 3D plots. I'm so sorry if I have missed anything

Thanks!

**Comment by facontidavide** [comment]
Not possible, sorry 😕
