### ISSUE TITLE
NaN in JSON is not parsed correctly

### ISSUE THREAD

**Issue by pavel-kirienko** [facontidavide/PlotJuggler#640]
Per the JSON specification, NaN floats cannot be represented natively, so many encoders substitute NaN with null. One would expect PJ to handle null values in JSON input as NaN for compatibility with this common case. Instead, we get this:

<img width="350" alt="image" src="https://user-images.githubusercontent.com/3298404/167270103-948c180e-bbf0-4aca-8081-1dd72bc447e7.png">

The JSON doc I used is:

```json
{
  "1252": {
    "timestamp": {
      "microsecond": 0
    },
    "value": {
      "current": {
        "ampere": null
      },
      "voltage": {
        "volt": 24.852617263793945
      }
    }
  }
}
```

**Comment by facontidavide** [comment]
I updated the JSOn parse and I think this fixed the issue

**Comment by pavel-kirienko** [comment]
@facontidavide Thanks! But the issue is still there though :D

**Comment by facontidavide** [comment]
sorry to hear that. I will try to address it in the next release

**Comment by facontidavide** [comment]
I have just tried and it works just fine
![image](https://user-images.githubusercontent.com/2822888/184040594-0972e95b-2a26-45cc-a772-8c7ccc24afff.png)

Closing not being reproducible
