### ISSUE TITLE
Drag a group of time series to the plotting area

### ISSUE THREAD

**Issue by pavel-kirienko** [facontidavide/PlotJuggler#641]
Say, I have multiple values in the time series tree under the same root, like `/foo/bar` and `/foo/baz`. I would like to visualize both of them, so I drag `/foo` into the plotting area expecting it to add both `/foo/bar` and `/foo/baz`. Is it something that could eventually be supported?

**Comment by facontidavide** [comment]
I could, but I don't want to :slightly_smiling_face: 

It is not unlikely for /foo to have dozens of children. I think it would be frustrating, eventually.
