### ISSUE TITLE
[usability] plot all positions of joint set

### ISSUE THREAD

**Issue by v4hn** [facontidavide/PlotJuggler#643]
Hey @facontidavide , I promised you in person to report this at least a year ago. Guess I finally manage...
Observed on ROS noetic / PlotJuggler 3.4.3 and earlier.

Before the "big" revamp of the GUI it was straight-forward to select all positions for a set of joints, by searching for a substring of the joint and "pos", selecting all entries as a group and dragging them to the plot.

With the newer GUI this is quite tedious. I can still search for, e.g., "r_ pos", but this is the result:
![tmp4](https://user-images.githubusercontent.com/680358/167390462-fb63082a-de0a-4036-826c-dbf2989facc1.png)

Now I have to double click all joints I'm interested in to finally select pos in each of them:
![tmp5](https://user-images.githubusercontent.com/680358/167390540-d3d6e25b-ff20-421b-a542-a1b2c3179736.png)
Group selection via holding shift works, but you actually have to click "position" somewhere because the joint names are not actually selectable *and* the joint entries have to be unfolded already. With many joints and trying to plot position/velocity/effort for them this is very tedious.

**Comment by facontidavide** [comment]
try unchecking this

![image](https://user-images.githubusercontent.com/2822888/168417919-dba65a53-0bc4-4535-a376-a797f76f1b93.png)

**Comment by v4hn** [comment]
:+1: Thank you. I didn't consider you actually made it optional.
Minor issue: Disabling this option with a loaded dataset will not change the layout of the new dataset and adding the same dataset again will leave the screen with a mixture of tree-structured items and a plain list in the view on the left.
