### ISSUE TITLE
Hello,

### ISSUE THREAD

**Issue by M-Fatih-Ozkan** [facontidavide/PlotJuggler#645]
Thanks for contributing to PlotJuggler. You are great!

# Problem description

Describe the problem and the expected behavior. Use screenshots of video if approriate.

# Steps to reproduce (important)

- Describe your platform / Operative System.
- Check if the problem can be reproduced using the dummy data created by the command line argument "-t" or one of the files in the folder "datasamples".
- If it can't be reproduced with the dummy data, __please__ share the CSV file or the rosbag that can be used to reproduce the problem.

**Comment by facontidavide** [comment]
There is no issue here

**Comment by M-Fatih-Ozkan** [comment]
> There is no issue here

Sorry, I updated now
