### ISSUE TITLE
Comparison Features

### ISSUE THREAD

**Issue by m-fatihozkan** [facontidavide/PlotJuggler#646]
Hello,

Thx for plotjuggler,

I need some practical solutions and also answers;

I am using plotjuggler for px4 log files. And for comparison with other things i need the time with minute display like this:

![image](https://user-images.githubusercontent.com/76562153/167580661-17e40ad6-b8bd-4186-b401-5ff0cd4b7506.png)

minute:second as shown. It is not an important situation, it would be good if this situation can be achieved with a button.

There is a necessary addition for me to (can see on image) matching the flight modes with plot. It would be better for long flights. At least it can be shown on plot with horizontal lines like this:

![2022-05-1011:00:32](https://user-images.githubusercontent.com/76562153/167580776-6759b63f-dc6a-42d1-8b19-3b39053a375b.png)

Can we plot 2 time series on same plot or in same tab from different ulg files for comparing flights.
Can we filter data with some specification like: Show where the airspeed is 30.
I will be glad if you can help.

**Comment by M-Fatih-Ozkan** [comment]
@facontidavide Hello, it's been a while can you help me?

**Comment by facontidavide** [comment]
no, sorry, what you describe is not supported
