### ISSUE TITLE
why the topic in the list can not be drag ?

### ISSUE THREAD

**Issue by JACKLiuDay** [facontidavide/PlotJuggler#648]
Thank you for your great work.
![image](https://user-images.githubusercontent.com/30967867/167765135-842adf31-ea90-4524-8d39-e258d4360c74.png)
I can not drag the topic in the list to the plot area, why?

**Comment by JACKLiuDay** [comment]
![微信图片_20220511140847](https://user-images.githubusercontent.com/30967867/167781026-70b0e553-39ff-4648-ba8c-a09e33d9767e.jpg)

When i tried to drag with left mouse button, it became a stop sign.

**Comment by facontidavide** [comment]
it should work if you continue the dragging motion until you reach the plotting area

**Comment by JACKLiuDay** [comment]
![image](https://user-images.githubusercontent.com/30967867/167794913-3916249f-7ca6-4df4-93e1-44781db41209.png)
Hi, I tried the dragging motion until I reach the table area, but it still is the stop sign. Once I push the left mouse button on the x topic , it would become stop sign no matter where I drag it.

**Comment by JACKLiuDay** [comment]
> which version of PJ are you using? How can I reproduce this? do the other series work?

Hi, I found the reason. I am using PJ with ros by sudo apt install ros-melodic-plotjuggler-ros. My QT is 5.12.0. I changed it to the QT5.9.5, and it worked! Thank you so much for your reply and your great work!
