### ISSUE TITLE
Can it draw multiple Y-axis curves like Ni diadem？

### ISSUE THREAD

**Issue by likangbei** [facontidavide/PlotJuggler#651]
Hi！facontidavide
Can it draw multiple Y-axis curves like Ni diadem？
![1653230276(1)](https://user-images.githubusercontent.com/4989210/169700832-5585d8b7-1670-4577-ae3a-87e7fe48c542.png)

Now the x-axis cannot be aligned, and a lot of space is wasted in the vertical direction
![1653230475(1)](https://user-images.githubusercontent.com/4989210/169701002-d981a243-26f6-4f47-aa77-43d9c5837c0f.png)

**Comment by facontidavide** [comment]
Nope
