### ISSUE TITLE
github-repo-stats causes checkout to fail on Windows

### ISSUE THREAD

**Issue by Bartimaeus-** [facontidavide/PlotJuggler#652]
The recent github-repo-stats addition seems to cause an invalid file path for Windows that leads to the following error (cmd line output):

git clone https://github.com/facontidavide/PlotJuggler
Cloning into 'PlotJuggler'...
remote: Enumerating objects: 17134, done.
remote: Counting objects: 100% (2496/2496), done.
remote: Compressing objects: 100% (1114/1114), done.
remote: Total 17134 (delta 1488), reused 2143 (delta 1323), pack-reused 14638
Receiving objects: 100% (17134/17134), 51.46 MiB | 12.46 MiB/s, done.
Resolving deltas: 100% (11518/11518), done.
error: invalid path '.github/workflows/- name: github-repo-stats   uses: jgehrcke/github-repo-stats'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

Seems that the issue is from the use of colons in '- name: github-repo-stats   uses: jgehrcke/'

The result on Windows is that the new directory only contains the .git folder and none of the source files. No issues found when cloning in a VM running Ubuntu, but a solution for Windows would be appreciated

**Comment by facontidavide** [comment]
removed
