### ISSUE TITLE
Transform editor resets plot zoom after any adjustment is made

### ISSUE THREAD

**Issue by Bartimaeus-** [facontidavide/PlotJuggler#655]
The zoom on the plot view in the transform editor is reset after any change in value or selection is made, which can make it tedious to check the results

https://user-images.githubusercontent.com/2954254/170838008-2e7bb175-e88d-4b3f-ad1f-d045c8142dcf.mp4

This especially effects time offset transform configuration, where I often have the need to align the rising/falling edge of multiple signals. Request that the zoom is not changed unless requested by the user

**Comment by facontidavide** [comment]
Unfortunately, for any situation where zooming out is annoyng, I can think about one where non doing it is annoying too.
I guess the solution is to add an autozoom checkbox

**Comment by facontidavide** [comment]
Done

**Comment by lucasw** [comment]
Found the solution under `App | Preferences | Behavior`, unchecked all of `Curve added to plot`, `Curve visibility toggled`, and `Filters applied to curves`

![plotjuggler_dont_reset_zoom](https://user-images.githubusercontent.com/1334122/217584543-d217f9f6-19ee-43e4-b447-49c8ad921f8a.png)

**Comment by facontidavide** [comment]
I didn't even remember that was implemented :smile:

**Comment by lucasw** [comment]
Looks like this PR came in a little later https://github.com/facontidavide/PlotJuggler/pull/704 than this issue (but this issue has better SEO in google apparently)
