### ISSUE TITLE
How to create ulog fromat file?

### ISSUE THREAD

**Issue by MaRongbo** [facontidavide/PlotJuggler#669]
# Problem description
PlotJuggler is the most powerful data visualization tool I have ever used.

My programming language is C++.  I want to use PlotJuggler to analysis my own log data,  so I should save my log as ulog format 

**But I don't find an exemple about how to write ulog, there is only the PX4't ulog format doc for me, and it is hard for me to write a ulog writer. I tried Migrate PX4's log code, but I failed because It's very complicated and depends on a lot of other code.**

**Is there simple way to write ulog format  that I don't know? Or could someone share your ulog writer code?** 

Many thanks!

**Comment by facontidavide** [comment]
Hi, you should ask this question in the PX4 forums / issues, not here.

Cheers

**Comment by tadashi-hamada196** [comment]
@MaRongbo have you find a solution? same problem here

**Comment by heatMa** [comment]
> @MaRongbo have you find a solution? same problem here

you can refer this repo https://github.com/PX4/pyulog.
And I writed a blog last year, maybe helpful for you.
