### ISSUE TITLE
Debug output for Lua scripts

### ISSUE THREAD

**Issue by nicholas-p1** [facontidavide/PlotJuggler#675]
# Problem description

It is hard to debug Lua scripts. The only output is `The Lua function cannot compute the result`.
Would it be possible to add an output field showing a simple debug trace? An output for print statements would be excellent.

I don't write Lua code regularly, so I often make simple mistakes that are hard to spot without any debug output.

# Steps to reproduce (important)

Create a custom series using Lua and write failing code.

**Comment by facontidavide** [comment]
I have some ideas about how to improve that. I will keep you updated

**Comment by facontidavide** [comment]
![image](https://user-images.githubusercontent.com/2822888/176378562-301e18c8-9c68-420e-9f4b-637e0e2ed3f3.png)

**Comment by nicholas-p1** [comment]
Thank you for implementing this so rapidly!
