### ISSUE TITLE
PlotJugglerConfig.cmake.in Case-sensitive issue with Windows

### ISSUE THREAD

**Issue by Bartimaeus-** [facontidavide/PlotJuggler#677]
There are two files in the repo that have case-sensitive names, which causes the following issue when using git to clone the repo on Windows:

warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'PlotJugglerConfig.cmake.in'
  'plotjugglerConfig.cmake.in'

Can one of these be renamed?

**Comment by facontidavide** [comment]
fixed this
