### ISSUE TITLE
Plotjuggler crashes when trying to apply filter to data

### ISSUE THREAD

**Issue by Bartimaeus-** [facontidavide/PlotJuggler#684]
Plotjuggler crashes when trying to apply a filter to time series in the 3.4.5 release for Windows.

This issue also appears to be present in 3.4.4

Example setup that causes crash:
![image](https://user-images.githubusercontent.com/2954254/178355909-47762090-cd5b-4cd5-96a6-24ece80df7b1.png)

Sample csv file:
[motor_data.csv](https://github.com/facontidavide/PlotJuggler/files/9087477/motor_data.csv)

**Comment by facontidavide** [comment]
Thanks for reporting, I will try to address this ASAP

**Comment by facontidavide** [comment]
I was able to reproduce it on older versions, but not the latest. I think this is related to Lua, but I am having an hard time understanding why

**Comment by facontidavide** [comment]
I believe this was fixed. If it isn't, let me know
