### ISSUE TITLE
Plotjuggler crashes when trying to save color map script with syntax errors

### ISSUE THREAD

**Issue by Bartimaeus-** [facontidavide/PlotJuggler#687]
Trying to save a ColorMap with invalid lua script content causes Plotjuggler to crash in v3.5.0

Things like bad syntax or not returning a value will cause Plotjuggler to crash when attempting to save the color map
Example:
![image](https://user-images.githubusercontent.com/2954254/178595434-e966d668-1249-4022-b97f-9dd1759abfb8.png)

Perhaps adding the red/green dot check as done elsewhere would be a good fix
![image](https://user-images.githubusercontent.com/2954254/178595778-c7ca236c-07dd-4272-9240-4bf492c255ee.png)

The color map feature is pretty great so far despite this issue, glad to see this feature

**Comment by facontidavide** [comment]
Is this happening in windows or Linux?

**Comment by Bartimaeus-** [comment]
Windows 10. Have not tested on Linux
![image](https://user-images.githubusercontent.com/2954254/178773059-dd23f358-3fec-4cce-8015-eb3f80d2ae89.png)
