### ISSUE TITLE
Segmentation fault after building from source

### ISSUE THREAD

**Issue by shekharsumanpatel** [facontidavide/PlotJuggler#696]
Thanks for contributing to PlotJuggler. You are great!

# Problem description
When i launch plotjuggler after building it form soource i get segmentation fault.
Describe the problem and the expected behavior. Use screenshots of video if approriate.
![image](https://user-images.githubusercontent.com/30315558/179558791-82f1ae8f-c3e9-4e12-9de2-ca9f7a2c675d.png)

# Steps to reproduce (important)
I just followed the steps mentioned in the readme

- Describe your platform / Operative System.
-Operating System:Debian GNU/Linux bookworm/sid
-Kernel: Linux 5.18.0-1-amd64
-Architecture: x86-64

Thanks and best regards ;)

**Comment by facontidavide** [comment]
Unfortunately this tells me very little. Can you please compile it in debug mode? That will send more information

**Comment by shekharsumanpatel** [comment]
![image](https://user-images.githubusercontent.com/30315558/179689001-90cb605e-38d2-44b6-92df-4b569a1db384.png)

**Comment by facontidavide** [comment]
I am not sure why this is happening, but I just pushed a change that should fix this

**Comment by shekharsumanpatel** [comment]
Thank you so much Davide. It works now. :)
