### ISSUE TITLE
MutableScatterXY.new("xxx") failed in the reactive script

### ISSUE THREAD

**Issue by TakaHoribe** [facontidavide/PlotJuggler#699]
# Problem description
Thanks for the great work of the PlotJuggler.

I used the reactive script following [the tutorial.](https://slides.com/davidefaconti/plotjuggler-reactive-scripts/fullscreen#/6) It worked very well in the old version of the binary release of `ros-galactic-plotjuggler` (`3.4.2-1focal.20220430.111249`), but after the version upgrade to the latest: `3.4.4-1focal.20220517.013511`, it got failed with an error message as in the screenshot below.

After some tests, I found `MutableScatterXY.new("xxx")` could be a problem.

# Steps to reproduce (important)

 - OS: x86_64 Ubuntu20.04 5.15.0-41-generic
 - PlotJuggler Version: `3.4.4-1focal.20220517.013511`

Write the following code in the function area and save it.
```lua
new_series = MutableScatterXY.new("xxx")
```

![image](https://user-images.githubusercontent.com/21360593/180215856-629417ee-1f85-4a33-bfd3-68d74aaf995b.png)

Start subscribing a ros topic. I just published the twist with following command and subscribe in the plotjuggler.
```
ros2 topic pub /cmd_vel geometry_msgs/msg/Twist "{}" -r 1
```

And then the error message will pop up every time the topic is received.

![image](https://user-images.githubusercontent.com/21360593/180215767-62bb2c2e-2179-48c6-8f03-566d37a258e9.png)

---

## checks in other versions

I checked with different versions from source build
- 3.4.2: OK (no error). Same as binary install.
- 3.5.0: NG (error)
- main (d2b6b73bb7b4eb7dcf795e3f207c7543428fff05):NG (error)

**Comment by facontidavide** [comment]
I will try to address this ASAP

**Comment by facontidavide** [comment]
This was renamed in February "ScatterXY"
