### ISSUE TITLE
Cannot view historical data

### ISSUE THREAD

**Issue by Hardliu** [facontidavide/PlotJuggler#701]
Thanks for contributing to PlotJuggler. You are great!

# Problem description
When I replay my bag and use the streaming to analyze data, I just to look 5 seconds data, cannot view historical data.

![image](https://user-images.githubusercontent.com/53360645/180677618-243d4545-3a70-463b-bc43-2c00b795901e.png)

**Comment by facontidavide** [comment]
have you increased the streaming buffer?
