### ISSUE TITLE
[Feature Request] ROS2 use user defined interfaces

### ISSUE THREAD

**Issue by lalaorome** [facontidavide/PlotJuggler#706]
Hi,

First of all, thank you for your great work, PlotJuggler is an amazing tool !

I thought that it would be really nice to be able to import our own user designed interfaces repository to allow PlotJuggler to recognize them. Currently it seems that the application is only looking at the ros repo.

I don't know if this feature is available but I couldn't find how to do it anywhere, however I am kinda of a newbie with PlotJuggler.

Thank you agin for your work

**Comment by facontidavide** [comment]
You can already do that. You just need to source your **install/setup.bash** (where custom types are defined) before starting PlotJuggler in the same console
