### ISSUE TITLE
Can't Compile with Cmake and Conan

### ISSUE THREAD

**Issue by m-fatihozkan** [facontidavide/PlotJuggler#711]
Hello,

# System in Use

- Ubuntu 18.04
- cmake version 3.10.2
- Conan version 1.51.0

# Problem description

I am following the COMPILE.md instructions, when I am trying to compile with cmake I am getting this error;

`>~/plotjuggler_ws$ cmake -S src/PlotJuggler -B build/PlotJuggler -DCMAKE_INSTALL_PREFIX=install`
Output:

```
CMake Error: The source directory "/home/fatih/plotjuggler_ws/build/PlotJuggler" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
```

Also I've tried with Conan but getting similar error:
```
cmake -S src/PlotJuggler -B build/PlotJuggler \
      -DCMAKE_TOOLCHAIN_FILE=$CMAKE_TOOLCHAIN  \
      -DCMAKE_INSTALL_PREFIX=install \
      -DCMAKE_POLICY_DEFAULT_CMP0091=NEW
```
Output:

```
CMake Error: The source directory "/home/fatih/plotjuggler_ws/build/PlotJuggler" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
```

I would be appreciated if you help.

**Comment by facontidavide** [comment]
I wonder if that is related to an older version of cmake. I am using Ubuntu 20.04

**Comment by ahar** [comment]
Hello,
I found the same compilation issue with ubuntu  18.04 and cmake 3.10.2. @facontidavide  can you please suggest a fix for this?

thank you,

**Comment by m-fatihozkan** [comment]
> I wonder if that is related to an older version of cmake. I am using Ubuntu 20.04

I handled the error with upgrading the cmake version. But now can't remember which version I updated. Like you said it is about cmake version.I will try again and I'll let you know.

**Comment by facontidavide** [comment]
actually, you don't need to upgrade cmake.

Just substitute the command 
```
cmake -S src/PlotJuggler -B build/PlotJuggler
```

with:

```
mkdir -p build/PlotJuggler
cd build/PlotJuggler
cmake ../src/PlotJuggler
```

**Comment by m-fatihozkan** [comment]
> actually, you don't need to upgrade cmake.
> 
> Just substitute the command
> 
> ```
> cmake -S src/PlotJuggler -B build/PlotJuggler
> ```
> 
> with:
> 
> ```
> mkdir -p build/PlotJuggler
> cd build/PlotJuggler
> cmake ../../src/PlotJuggler
> ```

Appreciate that.
