### ISSUE TITLE
need to access the historical data

### ISSUE THREAD

**Issue by brkay54** [facontidavide/PlotJuggler#720]
Thanks for contributing to PlotJuggler. You are great @facontidavide ! 

# Problem description

Hi, I need to access the historical data in plotjuggler (I used buffer as 100 that is max value). There is no need to plot them but just need to be able to export as cvs the historical data. Idk how to do this? Do you have any suggestion?

**Comment by brkay54** [comment]
https://github.com/facontidavide/PlotJuggler/issues/506#issuecomment-913114058 I know this comment, but I tried to increase `buffer_size` to 500 sec but I couldn't see the data in 500 sec range.

**Comment by facontidavide** [comment]
not possible. Data outside the buffer is lost forever.
Something that might be introduced in the future is file logging
