### ISSUE TITLE
Cannot compile on Windows using vcpkg

### ISSUE THREAD

**Issue by Bartimaeus-** [facontidavide/PlotJuggler#728]
**Issues with Compiling with directions from Compile.md**
I've tried to use the method given in [Compile.md](https://github.com/facontidavide/PlotJuggler/blob/main/COMPILE.md) using vkpkg, but there seems to be some sort of linker error that I have not been able to resolve.

-I've had this issue since the instructions were added to Compile.md but had not gotten around to making a ticket for it.

The output from running cmake is attached:    
[cmake_output.txt](https://github.com/facontidavide/PlotJuggler/files/9387748/cmake_output.txt)

See the link below for a .zip with the contents of the plotjuggler_ws directory:
https://drive.google.com/file/d/14gvtnTn2W7gLDzWKmVaoA0YBdobMAl78/view?usp=sharing

**Comment by facontidavide** [comment]
I will focus on **conan** only, supporting both is too much trouble for me and there is little value
