### ISSUE TITLE
[Bug] Figures are not saved, if the file extension is entered

### ISSUE THREAD

**Issue by 16stelter** [facontidavide/PlotJuggler#735]
# Problem description

When trying to save a figure, if the file extension is also entered into the file name field, the saving dialogue closes normally, but does not create the file.

# Steps to reproduce (important)

Platform: Ubuntu 22.04
1. Right click any plot and select 'Save plot to file'
2. Enter a file name with extension (e.g. 'plot.png')
3. Click save

**Comment by facontidavide** [comment]
I just tried and it works as expected
