### ISSUE TITLE
ZMQ Plugin not appearing with windows install 3.6.0

### ISSUE THREAD

**Issue by NateLovallo** [facontidavide/PlotJuggler#738]
# Problem description

Have tried installing 3.6.0 on a few different windows machines, ZMQ plugin never appears in the "Streaming" dropdown.
![image](https://user-images.githubusercontent.com/10678757/187745482-e375cdae-e9dc-4514-826a-62ebf9730200.png)

Installing on Ubuntu it appears just fine.
The DLL is present on my windows install folder. 

# Steps to reproduce (important)

Have tried on Wndows 10 Home/Professional.

Any way to easily look at logs on windows? Would love to help troubleshoot. Still looking into getting a build with vcpkg.

**Comment by facontidavide** [comment]
I will investigate

**Comment by facontidavide** [comment]
Fixed. I will upload the new executable shortly
