### ISSUE TITLE
[Feature Request] Support to scattered plot

### ISSUE THREAD

**Issue by proKgit** [facontidavide/PlotJuggler#776]
Not sure if it is possible to add support to 2D scattered plot. 

This may no be a "time series" but it can be updated every frame with a message of vector. Additionally it would be grate if the scattered point can be draw in different style such as circle/start/ etc.

and actually I expect to use this feature to visualize the 2d obj list :-D

**Comment by facontidavide** [comment]
right click + edit curves... + Lines style = Dots
