### ISSUE TITLE
axis is stick to [-0.1, 0.1]

### ISSUE THREAD

**Issue by congwu26** [facontidavide/PlotJuggler#78]
I used the streaming function, when I add the pose.x to the plot the y axis is somehow stick to [-0.1, 0.1] which I can not zoom in and out.

**Comment by facontidavide** [comment]
With so little information, it is hard to know what is going on. 
When the Y axis is not updated, most probably you are not receiving any message or all the values are 0.
Please provide more information:

1) Are you streaming using the ROS plugin or your own?
2) If it is ROS, can you share a rosbag and a __layout file__ to reproduce this behavior?

**Comment by v4hn** [comment]
Hey there,

I see the same problem with a particular `std_msgs/Float64` stream with the latest version available in kinetic over here.

Here are the files you requested. Notice that when the command value jumps back to 0 suddenly the limits are ok for a while... (until the jump leaves the observation window again).

[plotjuggler-stuck-limits.zip](https://github.com/facontidavide/PlotJuggler/files/1942214/plotjuggler-stuck-limits.zip)

**Comment by facontidavide** [comment]
I will take a look.

**Comment by v4hn** [comment]
Wow, impressive response time. :-)

**Comment by facontidavide** [comment]
You are welcome, I would have solved this sooner if @congwu26 shared his rosbag ;)
