### ISSUE TITLE
dragged topic sticks to pointer after drop

### ISSUE THREAD

**Issue by v4hn** [facontidavide/PlotJuggler#80]
I've been wondering about this behavior for quite some time now...
Not always, but on a regular basis, when I drag and drop a field from the list on the left to a plot, the name of the field still sticks to the pointer even after I released the mouse and the plot was added.

![screenshot from 2018-04-24 18-06-04](https://user-images.githubusercontent.com/680358/39180753-4d792296-47ea-11e8-807e-0a0e729eebe2.png)

Clicking anywhere on the screen resolves this, but it's still a bit annoying. 

A second problem with drag&drop, I'm not sure they are related so feel free to scold me for putting two problems in one issue, is that sometimes drag&drop simply fails.
On releasing the mouse button simply nothing happens. In this case I think I've always experienced that the label sticks to the pointer.

**Comment by facontidavide** [comment]
Hi

          sometimes drag&drop simply fails

That is a huge problem, I have been trying solving in several ways but I have no idea about why this happens :(

About the other problem (name of the topic sticks) I must investigate it if I find a way to reproduce it...

**Comment by v4hn** [comment]
*sigh* nice way to spend the evening...

So, I looked into it for quite a while and found a major problem.
[Qt already implements Model-View-based drag&drop for `QTableWidget`s](http://doc.qt.io/qt-5/model-view-programming.html#using-drag-and-drop-with-item-views). This is enabled in PlotJuggler [here](https://github.com/facontidavide/PlotJuggler/blob/master/plotter_gui/filterablelistwidget.ui#L333).
However, you do not use this system, but hacked your own on top of the [eventFilter](https://github.com/facontidavide/PlotJuggler/blob/master/plotter_gui/filterablelistwidget.cpp#L169) logic.
As a result both systems run in parallel and apparently it is not very well defined what happens when two `QDrag::exec` are called at the same time. Usually your override seems to win, but as I posted above, after the drop I still have the second drag associated with the pointer (standard ubuntu 16.04 install with ROS kinetic).

I tried disabling the `QTableWidget`s D&D and this works quite well.
*However*, that way your hack breaks the usual Qt signal processing even more and the TableWidget never realizes that it is not in drag-selection mode anymore after D&D. So the next click into the table counts as end of drag-selection and creates a weird selection of curves. Apparently the internal d&d took care of this earlier and I could not find an easy way to implement this in your logic.

I also tested the other way around and removed your logic in favor of the built-in system.
Because you use the ui-xml definition for the widget and the drag starts from the table widget,
this ends up looking quite weird, but it works too. You have to accept drops with format `application/x-qabstractitemmodeldatalist` (I'm not aware of a way to subclass an object from ui definitions and this is the default) from a source with name `tableWidget`.
Also, this way the decision whether the drop is a left or right click happens only during dropping in `plotwidget.cpp`. So this cannot easily include [the additional cursor decoration you setup on drag](https://github.com/facontidavide/PlotJuggler/blob/master/plotter_gui/filterablelistwidget.cpp#L217).

I think your best bet is to remove the ui file and implement the widget in source, subclass the table (or, better, create a new Qt model for model-view instead) and setup the drag&drop system for this object as explained in the first link in this post.

It would be great if you could look into this again with this additional information!

**Comment by facontidavide** [comment]
Hi, I am working on a different branch, https://github.com/facontidavide/PlotJuggler/tree/issue_80

Unfortunately no luck so far.

1) I disabled Dragging in the QTableWidget (in the __ui file__) and I was able to prevent the weird selection that you mentioned.

2) I am positive that the problem is not on the Drag side but the Drop one. Apparently Qwt invokes __erroneously__ the method __dragLeaveEvent()__ even if the mouse is located in the center of the canvas (it is not supposed to do that!!!). It looks almost random. To make it more visible, I change the background of the QwtPlot to light gray when we are ready to drop.

Look at the video

[dran_drop_plotjuggler-2018-04-25_01.00.47.mkv.tar.gz](https://github.com/facontidavide/PlotJuggler/files/1944882/dran_drop_plotjuggler-2018-04-25_01.00.47.mkv.tar.gz)

I will probably submit this issue to the Qwt mailing list and see if anyone can suggest a fix.

**Comment by v4hn** [comment]
I confirm that the branch resolves the double drag&drop issue and does not produce the selection artifacts I mentioned earlier. Great! I think these changes should go upstream.

Your observations on `dragLeaveEvent` being called by QwtPlot agree with my observations during debugging yesterday.
So yes, this is likely a bug in the library and not in your code.
Still it would be nice to report and fix it there :+1:

**Comment by facontidavide** [comment]
Unfortunately the maintainer of Qwt claims that this problem should be reported to Qt itself :(

Maybe one day I will switch to QCharts and check if this problem can be solved, but it is not on top of my TODO list. I will merge the branch **issue_80** soon.

**Comment by v4hn** [comment]
Argh. It should still be reported to Qt5 then I guess, but I do understand if you don't want to debug this through all of Qt5's core code...
And in this case it will not be fixed before ROS-n anyway...

Thanks for all your support and keep up the great work! :+1:

**Comment by facontidavide** [comment]
It look suspicious to me that such a huge bug is present in Qt itself and no one noticed. I still believe that it might be related to Qwt, but the maintainer won't investigate it :( 

Cheers

**Comment by v4hn** [comment]
Nah, that kind of thing happens way more often than people think in my experience.
It could very well be a bug in Qt.

> I still believe that it might be related to Qwt, but the maintainer won't investigate it :(

It's called open source for a reason.
I'm sure they accept tested patches. ;)

**Comment by facontidavide** [comment]
I am please to say that this ugly bug has been fixed... modifying some code on the Qwt side.
I am very happy, this was the most annoying problem I had since the beginning of the project.

Cheers
