### ISSUE TITLE
PlotJuggler screen stays black after starting

### ISSUE THREAD

**Issue by njoye** [facontidavide/PlotJuggler#802]
# Problem description
After starting PlotJuggler the window is black, nothing is displayed. A error is shown that the `librosx_inspection.so` file could not be loaded.

### Logs
```
timomueller@timomueller-QEMU-Virtual-Machine:~/catkin_ws$ rosrun plotjuggler plotjuggler -t
Loading compatible plugins from directory:  "/opt/ros/noetic/lib/plotjuggler"
"libDataLoadCSV.so is a DataLoader plugin"
"libDataLoadMCAP.so is a DataLoader plugin"
"libDataLoadULog.so is a DataLoader plugin"
"libDataStreamSample.so is a DataStreamer plugin"
"libDataStreamUDP.so is a DataStreamer plugin"
"libDataStreamWebSocket.so is a DataStreamer plugin"
"libDataStreamZMQ.so is a DataStreamer plugin"
"libParserROS1.so" :  "Cannot load library /opt/ros/noetic/lib/plotjuggler/libParserROS1.so: (librosx_introspection.so: cannot open shared object file: No such file or directory)"
"libParserROS2.so" :  "Cannot load library /opt/ros/noetic/lib/plotjuggler/libParserROS2.so: (librosx_introspection.so: cannot open shared object file: No such file or directory)"
"libPublisherCSV.so is a StatePublisher plugin"
Type conversion already registered from type QString to type QwtText
"libToolboxFFT.so is a Toolbox plugin"
Type conversion already registered from type QString to type QwtText
"libToolboxLuaEditor.so is a Toolbox plugin"
Type conversion already registered from type QString to type QwtText
"libToolboxQuaternion.so is a Toolbox plugin"
Number of plugins loaded:  11 

Loading compatible plugins from directory:  "/opt/ros/noetic/lib/plotjuggler_ros"
Number of plugins loaded:  0 

Loading compatible plugins from directory:  "/home/timomueller/catkin_ws/devel/lib/plotjuggler_ros"
Number of plugins loaded:  0 

Loading compatible plugins from directory:  "/home/timomueller/.local/share/PlotJuggler"
Number of plugins loaded:  0 
```

### Screenshot
![Bildschirm­foto 2023-03-07 um 11 20 16](https://user-images.githubusercontent.com/14947522/223393886-96d73991-9f98-45b0-be8d-7f2b633148a1.png)

# Steps to reproduce
### OS
Ubuntu 20.04 ARM VM (ROS Noetic) running on an M2 MacBook Pro. I was able to recreate the issue with a x64 install using virtualization so I don't think the platform is the problem.

### Steps
- Fresh install of ROS Noetic (`ros-noetic-desktop-full`)
- Installation of ROS using `sudo apt install ros-noetic-plotjuggler`
- Run PlotJuggler `rosrun plotjuggler plotjuggler`

**Comment by njoye** [comment]
@zdavkeos Works perfectly, thank you very much. Is there a way to use this flag permanently or do I need to fix something concerning my OpenGL installation?

**Comment by njoye** [comment]
@zdavkeos  I seem to be missing the ROS plugins though - is there a way to fix that ? I assume it has to do with the `"libParserROS1.so" :  "Cannot load library /opt/ros/noetic/lib/plotjuggler/libParserROS1.so: (librosx_introspection.so: cannot open shared object file: No such file or directory)"` error message.

**Comment by facontidavide** [comment]
happy ending...
