### ISSUE TITLE
Re-addition of pal_statistics_msg plugin

### ISSUE THREAD

**Issue by Noel215** [facontidavide/PlotJuggler#814]
Hi!!

The `pal_statistics_msg` plugin for PlotJuggler was removed [here](https://github.com/facontidavide/PlotJuggler/commit/0d19c30bc74ee59db849002daf1e01955419c880#diff-8b8bcd139bdbcf8f3b2f9bebd622d61d739a2a6675e9c1ca45c1105ecde9dcdd) and has not been re-added for the new version.

Would it be possible to get it back for both ROS and ROS 2??

**Comment by facontidavide** [comment]
Hi,
this issue should be moved to https://github.com/PlotJuggler/plotjuggler-ros-plugins

pal statistics IS supported: 

https://github.com/PlotJuggler/plotjuggler-ros-plugins/tree/rolling/plugins/ros1_parsers
https://github.com/PlotJuggler/plotjuggler-ros-plugins/tree/rolling/plugins/ros2_parsers

**Comment by Noel215** [comment]
Thank you so much! :) I didn't know about that repository
