### ISSUE TITLE
OpenGL issue with Intel Arc A750 Graphics Card

### ISSUE THREAD

**Issue by jodle001** [facontidavide/PlotJuggler#818]
When using plotjuggler with OpenGL using the Intel Arc A750, it appears to stop working properly.  The graph lines do not show up, and sometimes there are random glitches of lines or shapes on the screen inside the graph.

If I un-check OpenGL and run plotjuggler the lines show up fine. 

My Setup:
uname -r
6.3.0-060300-generic

glxinfo -B
name of display: :1
display: :1  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel (0x8086)
    Device: Mesa Intel(R) Arc(tm) A750 Graphics (DG2) (0x56a1)
    Version: 23.1.0
    Accelerated: yes
    Video memory: 8128MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) Arc(tm) A750 Graphics (DG2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 23.1.0-devel (git-722bcd7973)
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 23.1.0-devel (git-722bcd7973)
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 23.1.0-devel (git-722bcd7973)
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

- Check if the problem can be reproduced using the dummy data created by the command line argument "-t" or one of the files in the folder "datasamples".
- If it can't be reproduced with the dummy data, __please__ share the CSV file or the rosbag that can be used to reproduce the problem.

**Comment by facontidavide** [comment]
sorry, I have no idea how to fix that
