### ISSUE TITLE
Build Issues with CMake >= 3.26.0

### ISSUE THREAD

**Issue by aschneuw** [facontidavide/PlotJuggler#820]
# Problem description

When building with CMake >= 3.26.0 the dependency build QCodeEditor fails with a compilation error (QT include libraries)

# Steps to reproduce (important)

- Same Dockerfile as in master with the following changes:
- - using cmake from (https://pypi.org/project/cmake/3.26.0/)
- - ubuntu 20.04 base image instead of 18.04

# Workaround
Add -std=c++11 to 3rdparty/QCodeEditor/CMakeLists.txt target_compile_options

if(CMAKE_COMPILER_IS_GNUCXX)
    target_compile_options(QCodeEditor
                PRIVATE
                -ansi
                -pedantic
                -Wall
                -Wextra
                -Weffc++
                -Woverloaded-virtual
                **-std=c++11**
                -Winit-self
                -Wunreachable-code
        )
endif(CMAKE_COMPILER_IS_GNUCXX)

**Comment by zdavkeos** [comment]
I can confirm the suggested change works. I suggest making a pr.
