### ISSUE TITLE
Custom Calculation / Transform

### ISSUE THREAD

**Issue by CesMak** [facontidavide/PlotJuggler#84]
Hey there,

I would like to say that it would be a really nice feature if the incoming data streams could be used to do small calculation's as well and plot these calculations.

e.g.: Plot the difference between two incomming data streams 
It easily should be added an error transformation besides the 1, 2 deviation transformation :) 

Thanks :)

**Comment by facontidavide** [comment]
Hi @CesMak ,

you read my mind. What you described is a big update that I want to introduce in PlotJuggler 2.0.

Unfortunately, I am not able to start working on PlotJuggler 2.0 until  find a way to support this effort economically.
I am planning to start a sort of "mini-crowdfunding" to fund this effort.

Stay tuned ;)

**Comment by romainreignier** [comment]
@facontidavide This feature would be a very nice improvement to PlotJuggler. Could you share your plan about this feature, maybe we could help you to achieve this goal.
For example, to interpret the formulas, do you want to use an interpreted language like Lua or Python? And about the GUI, have you already though about how to select the streams to compute together?

**Comment by facontidavide** [comment]
Yes, my idea is to use Lua to create custom formulas. This also imply some kind of editor
The use cases I want to take into account are:

1) Should support both static data (loaded from file) and real-time data (streaming)
2) The custom function should access the entire time series, not only a time point. 

In other words, it should be possible to:

- Calculate the integral or derivative of a single series.
- Compute the average of N series.
- Convert a quaternion (4 series) to roll pitch yaw ( three series).

To keep it simple and efficient, I guess the best approach is to create a new series. It is NOT, therefore a property of a PlotWidget (as it currently is for the 1st and 2nd order derivative transform).

**Comment by romainreignier** [comment]
Thank you @facontidavide 
We will see if we can start something in this direction.

**Comment by facontidavide** [comment]
Development moved to branch https://github.com/facontidavide/PlotJuggler/tree/custom_plot2
