### ISSUE TITLE
ROS Kinetic Missing Plugin Libraries

### ISSUE THREAD

**Issue by evanglasgow** [facontidavide/PlotJuggler#85]
Hello!

Upon updating to the most recent version of plotjuggler provided by the ROS APT system (`1.6.0-0xenial-20180501-141149-0800`), I noticed an issue where the plugin libraries appear to be missing. The system location `/opt/ros/kinetic/lib/plotjuggler/` only contains the the PlotJuggler application and none of the lib*.so plugins. So when attempting to open a bag file an error message appears that no plugin is available for that operation.

**Comment by facontidavide** [comment]
Hi,

I will check it out, thanks for reporting

**Comment by evanglasgow** [comment]
Thanks for looking into this so quickly! I'll keep an eye out for the next ROS package sync and compile it manually until the new release is available.

**Comment by wangxiuzhong** [comment]
Hello!
I also encountered the same problem,could you tell me how compile it ?
I have tried to compile it by setting (COMPILING_WITH_CATKIN 1) in _CmakeLists.txt_ file,and it does not  work.The results in my console like this:
![2018-05-26 03 39 03](https://user-images.githubusercontent.com/30830961/40549701-c3c5bca0-606a-11e8-8bc1-5852ec944b49.png)

Thanks!

**Comment by facontidavide** [comment]
Hi,

**you must NOT set COMPILING_WITH_CATKIN manually.**

That variable is set __automatically__  if you are compiling using catkin as you would do with any other ROS package, i.e. inside a catkin workspace.

You can use either catkin_make or catkin build.

**Comment by wangxiuzhong** [comment]
Thank you for your reply !
I already use catkin_make in my workspace.However, no executable file was generated:
![2018-05-26 20 57 10](https://user-images.githubusercontent.com/30830961/40574537-932089f8-6106-11e8-9585-e4901dab9889.png)

Sorry to bother you again!

**Comment by facontidavide** [comment]
No problem, i am here to help!

I found it. The problem is in the WHITELIST.

The name of the package is **plotjuggler** (lower characters) not **PlotJuggler**

**Comment by facontidavide** [comment]
No problem, i am here to help!

I found it. The problem is in the WHITELIST.

The name of the package is **plotjuggler** (lower characters) not **PlotJuggler**

**Comment by wangxiuzhong** [comment]
It works! Thank you very much for your help! :)

**Comment by gavanderhoorn** [comment]
@facontidavide wrote:
> I think I know what happened. Unfortunately we need the ROS people to sync the new version 1.6.2 and it will probably take few weeks. Until than, you must compile it yourself :(

Just configure `apt` to download pkgs from `ros-shadow-fixed` instead of `ros`. That is the recommended procedure to install staged updates.

See [wiki/ShadowRepository](http://wiki.ros.org/ShadowRepository).

**Comment by gavanderhoorn** [comment]
I can confirm that `1.6.2` fixed this.

And it wasn't just an issue with the Kinetic release, Indigo was/is affected as well.

**Comment by facontidavide** [comment]
OK
