### ISSUE TITLE
The meme hides startup errors

### ISSUE THREAD

**Issue by AlexisTM** [facontidavide/PlotJuggler#868]
# Problem description

When a problem happened at boot (such as "missing package [plotjuggler-ros]"), the meme is in front.

Closing the error is enough to continue, but I only understood there was an error when a smaller meme was loaded. 

# Steps to reproduce (important)

- OS: Apertis Pro VM, Debian Bullseye fork with ROS 2 Galactic and this repo built from source
- Do not install plotjuggler-ros and start plotjuggler with `ros2 run plotjuggler plotjuggler`

This triggers the error `missing package [plotjuggler-ros]`, preventing plotjuggler to start, but the error is hidden behind the meme.

[Pro: It makes us enjoy the memes longer]

**Comment by salmagro** [comment]
Disabling the meme could be an option. See: https://github.com/facontidavide/PlotJuggler/blob/a5246dc88ca9b59d009cc9e4550ae2fac53a222d/plotjuggler_app/main.cpp#L379
