### ISSUE TITLE
PlotJuggler as RVIZ PLUGIN

### ISSUE THREAD

**Issue by CesMak** [facontidavide/PlotJuggler#87]
A really nice to have plugin in RVIZ would be PlotJuggler

thus see all the stuff images etc. etc. on one screen! So no one needs to switch between a PlotJuggler and Rviz window :) 

If you would develop such a feature it would be perfect :)

**Comment by facontidavide** [comment]
Hi,

First of all thanks for the suggestion, though. It is good to have a conversation about this kind of options and possible improvements.

It was suggested in the past to make PlotJuggler available as [rqt plugin](http://wiki.ros.org/rqt/Tutorials/Create%20your%20new%20rqt%20plugin) 
 but being frank, it is not on my agenda.

I understand the **theoretical** advantages, but I have two reasons for that:

1) PlotJuggler use a lot of real estate on the screen, it is hard to accommodate everything in my opinion. Few of us have a 38 inches screen  ;)

2) PlotJuggler is a desktop applications with it's own plugin. ROS is supported only by plugins and it will never be a hard dependency of the code application.

If someone feels adventurous he/she can try to implement this and share the results with a PR :)

Cheers

Davide

**Comment by facontidavide** [comment]
@VictorLamoine even if I am not supposed to help a competitor (just kidding... almost), I would like to suggest taking a look to my other package, **ros_type_introspection**, that allows an application like yours (and mine of course) to subscribe to ANY message and split it in individual time series.

**Comment by pfankhauser** [comment]
Sorry to chime in, but if you're interested, our plotting tool rqt_multiplot is available as rqt plugin:

http://wiki.ros.org/rqt_multiplot

-Péter

**Comment by facontidavide** [comment]
@pfankhauser 

![image](https://user-images.githubusercontent.com/2822888/43946044-5ce9405a-9c84-11e8-860c-c7b031317a0f.png)

**Comment by VictorLamoine** [comment]
I have opened an issue about ROS introspection: https://gitlab.com/InstitutMaupertuis/graph_rviz_plugin/issues/11

I don't need it (now) so I won't implement it but if someone creates a merge request I'll be happy to merge it. Thanks for the tip!

**Comment by facontidavide** [comment]
This will never happen. Closing the issue

**Comment by weird-bot-ros** [comment]
How about a rviz panel which can choose whether to load a bag or stream choosing the layout. 

In short the panel can have select mode to either load or stream. Choose a layout from the dropdown in the directory given in the label and click button which launches plotjuggler with these configuration.

I understand that u can always run plotjuggler in a terminal and manually choose layout or stream and select the data to stream. But having rviz panel kind of makes things a bit more convenient that we would generally have different rviz file for different domains like navigation, localization etc and each could save the rviz file accordingly and when time to debug data, open the panel and just click after selecting the configuration.

Is that a weird solution 😅😅 ?
