### ISSUE TITLE
Wrong date format when loading .csv file 

### ISSUE THREAD

**Issue by Zheqiu2023** [facontidavide/PlotJuggler#906]
Thanks for contributing to PlotJuggler. 

When I use plotjuggler to load a .csv file, there seems to be something wrong with the date format. Here is the plot:
![image](https://github.com/facontidavide/PlotJuggler/assets/92174893/820f2bc7-4d49-44cd-8551-17a8a8029218)
but when I load a bag file where the .csv file above comes from, the date format is correct.
![image](https://github.com/facontidavide/PlotJuggler/assets/92174893/6d2d9f16-5844-4d14-975b-47882b788e89)
I didn't modify the .csv file, so theoretically the data format should be right. 
Did I make a mistake at any steps? Could you please help me? 

I'm using ubuntu20.04 and the latest version of plotjuggler.

Here are the .csv file and bag file:
[cable_target_pos.csv](https://github.com/facontidavide/PlotJuggler/files/13839156/cable_target_pos.csv)
[updown.zip](https://github.com/facontidavide/PlotJuggler/files/13839162/updown.zip)

**Comment by facontidavide** [comment]
fixed
