### ISSUE TITLE
ros_parser.cpp issue with quaternion since 3.8.3

### ISSUE THREAD

**Issue by L0gi** [facontidavide/PlotJuggler#908]
in ros_parser.cpp after the refactor quternion "w" is published to "/z".

see file plotjuggler_plugins/ParserROS/ros_parser.cpp

line 205 -208

  getSeries(prefix + "/x").pushBack({ timestamp, quat.x });
  getSeries(prefix + "/y").pushBack({ timestamp, quat.y });
  getSeries(prefix + "/z").pushBack({ timestamp, quat.z });
  getSeries(prefix + "/z").pushBack({ timestamp, quat.w });

**Comment by facontidavide** [comment]
oh my god, thanks for reporting
