### ISSUE TITLE
Comparing Two ROS2 Bag Files with Same Topics Names

### ISSUE THREAD

**Issue by MortezaAliyari** [facontidavide/PlotJuggler#923]
Hi there,
In ubuntu20.04 ros1 melodic or neotic I can choose and open two bag files and by giving different prefixes I can compare two bag files with the same topic names. however in ubunut22.04 ros2 humble. I can't do the same.
How can i compare two or more bag files together in the same window with only running one Plotjuggler node?
thanks

**Comment by facontidavide** [comment]
With the introduction opf the new checkbox in version 3.8.7, you can now load them one by one.
