### ISSUE TITLE
Cannot edit properties of XY plot if multiple sources are loaded with prefix

### ISSUE THREAD

**Issue by peci1** [facontidavide/PlotJuggler#928]
# Problem description

When I open two bagfiles at once (with prefix) and create an XY plot from the loaded data, right-clicking and Edit curves shows this warning:

https://github.com/facontidavide/PlotJuggler/blob/e7b86387cfea6c8afacd6c1b304f0eb4b5e45ee8/plotjuggler_app/plotwidget.cpp#L838-L845

And there are no curves to be edited in the dialog.

# Answer these questions

1. Describe your platform / Operative System and the **version of PlotJuggler** you are using.

Main branch from today (3.8.10).

3. Compile and try the latest version in the **main** branch and check if the problem persists.

Checked.

5. Check if the problem can be reproduced using the dummy data created by the command line argument "-t" or one of the files in the folder "datasamples".

No, you need two sequences loaded with a prefix.

7. If it can't be reproduced with the dummy data, __please__ share the CSV file or the rosbag that can be used to reproduce the problem.

You can replicate it with these two CSVs: [files.zip](https://github.com/facontidavide/PlotJuggler/files/14067474/files.zip) . Open them both at once and create an XY plot from `file1/gnss/septentrio/fix/{latitude,longitude}`.

**Comment by facontidavide** [comment]
the explanation is pretty simple: you can not mix two timeseries in a XY plot unless they have EXACTLY the same timestamps and number of elements.

Not your case

**Comment by peci1** [comment]
I don't think you got it right. It suffices to add one xy series to the plot to trigger this issue. That still seems to be a bug to me.
