### ISSUE TITLE
Custom tooltip text for time series

### ISSUE THREAD

**Issue by Jofkos** [facontidavide/PlotJuggler#933]
# Problem description
I don't know if an issue is the right place to ask this if it isn't - please let me know.

I have data that would profit from a computed tooltip (so instead of just showing the number at the cursor position, replace that by a custom text which is a function of the value). From what I can tell, this is not possible with a custom series (please correct me if I am wrong here!) and I thus likely need to approach it with a custom plugin.

Is that actually possible, using a plugin, and applying it only to one specific time series? If it is, I'd greatly appreciate it if someone could point me into the right direction of how to approach this, as the plugin examples available aren't really covering a similar use-case.

**Comment by facontidavide** [comment]
No, the plugins that currently exist can't modify that part of the code.

I don't believe this will be implemented
