### ISSUE TITLE
Latest code crashes with old layout files

### ISSUE THREAD

**Issue by ssys-zdavis** [facontidavide/PlotJuggler#934]
# Problem description

A recent change:
https://github.com/facontidavide/PlotJuggler/commit/36cebbf680db4310720fd71846657b23ed52bbd9#r138442242

broke loading of old layouts that have a "Scale/Offset" transform applied. 

Describe the problem and the expected behavior. Use screenshots or a video, if applicable.

# Answer these questions (or I will ignore your issue)

1. Describe your platform / Operative System and the **version of PlotJuggler** you are using.
2. Compile and try the latest version in the **main** branch and check if the problem persists.
3. Check if the problem can be reproduced using the dummy data created by the command line argument "-t" or one of the files in the folder "datasamples".
4. If it can't be reproduced with the dummy data, __please__ share the CSV file or the rosbag that can be used to reproduce the problem.

1. Linux and Windows with latest `main`
2. It does (see 1)
3. Yes. Run with -t and open the attached layout file
4. -
[broken_layout.xml.txt](https://github.com/facontidavide/PlotJuggler/files/14214425/broken_layout.xml.txt)

**Comment by facontidavide** [comment]
Thanks for reporting... I did not think about that problem of back compatibility.

I will fix it soon
