### ISSUE TITLE
compile with error:"‘this’ was not captured for this lambda function"

### ISSUE THREAD

**Issue by supengufo** [facontidavide/PlotJuggler#938]
when i compile the repo with source code,i meet the error following:
/home/xxx/ws_plotjuggler/src/PlotJuggler/plotjuggler_base/include/PlotJuggler/transform_function.h:157:16: error: ‘this’ was not captured for this lambda function
               });

OS:ubuntu18.04
version:latest version

**Comment by facontidavide** [comment]
I am not supporting Ubuntu 18.04 anymore
