### ISSUE TITLE
Loading PlotJuggler without a datastream breaks my Layout

### ISSUE THREAD

**Issue by twostripe** [facontidavide/PlotJuggler#96]
When loading an existing layout (from the command line or gui) it appears that `PlotJuggler` needs to see messages of a certain type before its willing to make a curve for it.

Ex: If I had two topic `/position/x` and `/position/y` and tried to load a layout that had two plots (one for each), I would need to load a bag or be actively publishing on those topics. Otherwise `PlotJuggler` would effectively ignore my layout.

Is there a way to save a layout without data?

Is there a way to convince `PlotJuggler` to sit and wait for data, even if it's not being published yet?

Thank you.

**Comment by facontidavide** [comment]
Hi Mark,

I have never considered this option, because one of the activities of the Layout loading is to __try__ loading the original rosbag or to start the original streaming plugin.

in other words, if you created the layout as a result of loading a rosbag containing __position__, the same rosbag will be opened.

I guess that the solution, in your case, might be to create an empty placeholder timeseries (with zero points).

I will work on it in the next couple of days.

Cheers

**Comment by twostripe** [comment]
Although I must note, for posterity: the "easy" workaround is to open a layout & dataset at the same time from the command line, something `rqt_multiplot` cannot do. That's great for bags that have already been recorded, but for using this tool as a monitoring tool that breaks down pretty quick.

Thanks!

**Comment by facontidavide** [comment]
Hi,

please take a look at this branch  https://github.com/facontidavide/PlotJuggler/tree/issue_96

If you think that it does what you need, I will merge it.

Cheers

**Comment by twostripe** [comment]
Looks good! Thank you the quick turnaround.

I think that takes care of this and makes this tool more useful for me and my team. Multiple dialogues > one confusing dialogue, so I'm a fan of that change as well.

I'll use it for a few weeks then make some actual UI recommendations (or just do them myself and submit a PR).

**Comment by facontidavide** [comment]
I will probably merge the branch anyway, since I think more people will find this modification useful. 

By the way, I would like to ask you some questions about the way you and your team use PlotJuggler.
Would you ming share your email with me (mine is davide.faconti@gmail.com ).

Cheers

**Comment by MichalisPapadakis** [comment]
Hello, I am looking for the same functionality for a ROS2 application, but it seems it does not work. 

I am using PlotJuggler in a ROS2 application to visualize the outputs of different controllers. However, these controllers are not active at the same time. When I load a saved layout, if at the time of loading a topic does not publish data, then it is not added in the plots. When the topic becomes active at a later time, it is available as a time series, but it is not added automatically in the tabs. And as such, for each joint and each controller, i have to manually add it. 

Ideally, i would like to open a layout, and when data in the relevant topics are available, plotjuggler would add them in the plot window on its own. 

Is this functionality implemented in plotjuggler ROS2 and if yes, how can i achieve it? 


Thanks.
