### ISSUE TITLE
Can display mutil line type/style in one tab(plot area)

### ISSUE THREAD

**Issue by EyeeHKing** [facontidavide/PlotJuggler#997]
# Problem description
![image](https://github.com/user-attachments/assets/0e2f846a-a26d-43aa-81b1-035ea53bbcd4)

when plot multi curves,  all curve can only share the same line style, can we distinguish these curves, and more, can provide more line styles

**Comment by facontidavide** [comment]
I COULD, but I don't want to.
I value UI with a small number of options, over implementing all the features that people may need.
